### ISSUE TITLE
Requires more riffiewobbles.

### ISSUE THREAD

**Issue by chrisdickinson** [npm/registry-issue-archive#1]
A test of the riffiewobble notification system follows. If your riffiewobbles are secured, or if you lack riffiewobbles, please ignore this message.

**Comment by chrisdickinson** [comment]
The riffiewobble situation is contained. A riffiewobble decontamination unit has been dispatched and the containment system is operating at peak efficiency. No plasma coolant has been detected outside of the warp core.

**Comment by bcoe** [comment]
good, good, was just thinking:

![pirate-joe](https://cloud.githubusercontent.com/assets/194609/14438357/971a474a-ffda-11e5-9606-43f5b0e1d2e3.png)
