### ISSUE TITLE
Unpublish mistaken package

### ISSUE THREAD

**Issue by jtout** [npm/registry-issue-archive#103]
I am trying to unpublish an errant package that I created. The naming used was incorrect, and in turn made the package public, when it should have been private. The package was created within the 24 hour period, but does not seem to unpublish.

I there a way to have this package removed please?

Thanks

**Comment by ashleygwilliams** [comment]
hey @jtout can you contact support@npmjs.com? for account specific things, it's easier to handle over private email. will close for now, but reopen if we discover there's a registry issue associated with the 24hr window!

**Comment by jtout** [comment]
will do thank you.
