### ISSUE TITLE
online learning wrong input

### ISSUE THREAD

**Issue by calebebrim** [npm/registry-issue-archive#108]
I'm building searcher. I want develop a way to users classify the results as useful or not. My question is... when the the users classify like usefull and not useful the same result, the online training start to be a little lost; to log the result I use ".classifyAndLog" function each time the user classify an item; sometimes it does not return no class on log. I want to know what the purpose of this behaviour. It is not supposed to at least show the most accurate result.

**Comment by soldair** [comment]
I think you may have opened this issue on the wrong repository. you will need to contact that particular library author to get your question answered.

**Comment by calebebrim** [comment]
you are right... Sorry!
I'm having issue with other library.
