### ISSUE TITLE
New public package versions are not reflected in npme registry

### ISSUE THREAD

**Issue by wesleytodd** [npm/registry-issue-archive#111]
We run npme with the following applicable settings:

Upstream URL: https://replicate.npmjs.com
Policy to apply during replication: white-list

This morning a new version of a public package was published, and I tried to pull it down, but get the "No compatible version found" error.  I tried using `https://registry.npmjs.com/` as well, because I know we had used that in the past, still no go.  The package is installable from public npm.

Is it our settings or a bug?

Edit: current version is 26ddb02.  I know this is behind, but usually try not to update until slow times, because we have knocked out the entire instal multiple times we have tried to update, and I dont want to disrupt our work.  But I will try to push an update through tonight if that will help.

**Comment by wesleytodd** [comment]
This issue is blocking me on a few things.  I have emailed support but have not heard back.  Does anyone have information of this type of problem?

**Comment by soldair** [comment]
sorry you havn't heard back! i thought we had gone over all the tickets from last week.
can you tell me the value in the .sequence file in the data directory of your npme?
is it around 791923?
If this value is increasing and matches replication is working and there is another issue.
if the value is about a million higher then we need to reset the sequence. you can try running `npme reset-follower`. we may just want to reset the follower anyway.

**Comment by wesleytodd** [comment]
```
$ cat /storage/npm-onsite/data/sequence
756618
$ cat /storage/npm-onsite/data/sequence
cat: /storage/npm-onsite/data/sequence: No such file or directory
$ cat /storage/npm-onsite/data/sequence
19723
$ cat /storage/npm-onsite/data/sequence
53900
```

Look right?  It removed the sequence file, then replaced it with a much lower number that is increasing rapidly.

**Comment by soldair** [comment]
interesting. it should not have been stuck but if we find it sticks again maybe its choking on a particular event. In this case we can shut down npme advance the sequence by one and restart npme.
let me know how it goes =)

**Comment by wesleytodd** [comment]
Ok, so my sequence number is now 795817 and still growing.  How do I tell what the sequence number should be?  Is it the `"committed_update_seq": 1871969` from the root api request?

I ask because the package I am trying to install is still unavailable, but I am past the number you mentioned earlier.  

And thanks for your help!

**Comment by soldair** [comment]
just check that it matches the update_seq on https://replicate.npmjs.com
here is the couchdb doc for that object. 
http://docs.couchdb.org/en/2.0.0/json-structure.html#couchdb-database-information-object

committed_update_seq is more internal book keeping for couch and of no consequqnce for followers.

**Comment by wesleytodd** [comment]
Ok, it does match, `795916`, but the package is still not there.  The specific package is: https://www.npmjs.com/package/reconnectable-websocket

Here is the output I get in my npm install:

```
$ npm i
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: reconnectable-websocket@^0.1.10
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@streamme/streaming-socket'
npm ERR! notarget
```

**Comment by soldair** [comment]
we definitely need to start triaging in a support ticket. 
please email support@npmjs.org again. ill take over the ticket and lets see what we can do with more information.

**Comment by wesleytodd** [comment]
emailed!
