### ISSUE TITLE
Verify licenses

### ISSUE THREAD

**Issue by gjedeer** [npm/registry-issue-archive#114]
Let's take this project as an example:

https://registry.npmjs.org/StringScanner/

The license displayed on npmjs.org is MIT. Indeed:

    {"type":"MIT","url":"http://github.com/michaelficarra/cjs-string-scanner/raw/master/LICENSE"}

However, if you [check the link](https://raw.githubusercontent.com/michaelficarra/cjs-string-scanner/master/LICENSE), the license looks nothing like MIT, it's a 3-clause BSD license.

It would be nice if the registry verified common licenses for mismatches like this one.

**Comment by chrisdickinson** [comment]
We currently detect license type via the contents of [`package.json`](https://raw.githubusercontent.com/michaelficarra/cjs-string-scanner/master/package.json) — unless GitHub has already open-sourced a LICENSE corpus classifier, it's unlikely that we'll have the available cycles to build one ourselves in the foreseeable future. (If you know of one, that would be super helpful, though!)

**Comment by gjedeer** [comment]
https://developer.github.com/v3/licenses/#get-a-repositorys-license

Majority of npmjs projects are hosted on Github so, as impure as this solution is, it will work for most projects.

On February 8, 2017 8:09:56 PM CET, Chris Dickinson <notifications@github.com> wrote:
>We currently detect license type via the contents of
>[`package.json`](https://raw.githubusercontent.com/michaelficarra/cjs-string-scanner/master/package.json)
>— unless GitHub has already open-sourced a LICENSE corpus classifier,
>it's unlikely that we'll have the available cycles to build one
>ourselves in the foreseeable future. (If you know of one, that would be
>super helpful, though!)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/npm/registry/issues/114#issuecomment-278429925

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
