### ISSUE TITLE
README not detected (Sadly, this package has no readme. Go write one!)

### ISSUE THREAD

**Issue by erikerikson** [npm/registry-issue-archive#120]
Observed:
"Sadly, this package has no readme. Go write one!"

Expected:
The display of https://github.com/serverless/serverless/blob/master/README.md

As noted on https://github.com/npm/registry/issues/118, the README.md that exists is not being displayed.

This issue is tracked for the Serverless project here: https://github.com/serverless/serverless/issues/3157

One of the commenters there suggested adding `homepage` to `package.json` but despite that change being merged and the continued existence of a README.md at the root of the repo, this continues to be an issue:
<img width="1099" alt="screen shot @ '2017-01-30T18:59:55.486Z'" src="https://cloud.githubusercontent.com/assets/571200/22436961/fb7a0fb2-e6da-11e6-8f19-344a92372cb1.png">

**Comment by bcoe** [comment]
@erikerikson  looking at the serverless package, there is no README file in the contents:

<img width="1026" alt="screen shot 2017-01-30 at 10 39 05 am" src="https://cloud.githubusercontent.com/assets/194609/22436327/6b0b0546-e6d8-11e6-86fb-c8d43c745060.png">

There was a bug in older versions of npm (I see you published with 3.9.5) that caused README.md to sometimes not be included in the tarball generated. Try upgrading your npm version, and publishing a patch release of the module -- sorry for the inconvenience.

**Comment by erikerikson** [comment]
We weren't aware, I'll pass along the knowledge.  Thank you @bcoe!

**Comment by bcoe** [comment]
@erikerikson no worries 👍 I'm here all day, and I'm the one who's been doing most of the work on the README stuff -- so just keep me posted in this ticket and we'll get everything working for you.

**Comment by erikerikson** [comment]
Thanks @bcoe!  That was exactly the resolution.

**Comment by dhei** [comment]
Hi @bcoe, I encountered the same issue with our npm package (https://www.npmjs.com/package/mobile-center) not picking up the readme. We are using npm 4.6 and we are not yet ready to upgrade to npm 5+. Is the [npm bug you mentioned above](https://github.com/npm/registry/issues/120#issuecomment-276157329) exists in npm 4.6? Is there any workaround other than upgrading npm version?

Any help is much appreciated.

**Comment by bcoe** [comment]
Hey @dhei 👋 I looked at your repo, I believe you're bumping into a different issue.

You're using a mono repo structure, such that you publish `mobile-center` from the `mobile-center` sub-folder. This folder has no README contained within it, as a result not README is picked up and rendered. You can either:

1. have a build step prior to publication that generates a README in this folder, prior to calling `npm publish`.
2. permanently place a README in this folder.

Let me know if this does the trick for you.

**Comment by dhei** [comment]
@bcoe Thanks for the quick response! I will give it a try.

[Update 09/22/2017]: After putting README inside individual sub-folders, now it works.

**Comment by tommedema** [comment]
@bcoe my README.md is not detected either:

https://www.npmjs.com/package/final-html

but it shows just fine at runkit:

https://npm.runkit.com/final-html

**Comment by tangshuang** [comment]
@tommedema It seems you have fixed for your final-html, I am facing the same problem now, could you share how did you fix?

**Comment by tommedema** [comment]
@tangshuang I believe I published a new version, that fixed it.

**Comment by tangshuang** [comment]
@tommedema I have tried updating a patch version, it did not work. I give up.

**Comment by alditis** [comment]
Same problem.
```
npm publish
npm -v
5.5.1
```

Any suggestion?

**Comment by aearly** [comment]
@alditis what package?

**Comment by alditis** [comment]
https://www.npmjs.com/package/express-demo

Thanks for you comment.

**Comment by aearly** [comment]
The readme shows up on my end.  You might have caught the page before the readme was rendered.

**Comment by alditis** [comment]
Now I can see the readme. Thanks for your comments.

**Comment by xuechinahb** [comment]
me too !
npm 5.6.0

**Comment by givehug** [comment]
this problem solves after a few page refreshes

**Comment by AddoSolutions** [comment]
Could be too early to tell, but experieinceing this with my package as well:

https://www.npmjs.com/package/mac2ll

```shell
me@mycomputer (master)$ npm publish
+ mac2ll@1.0.3
me@mycomputer (master)$ npm -v
5.7.1
```

**Comment by tibinthomas** [comment]
I'm also facing the same for my ngx-img-zoom package. https://www.npmjs.com/package/ngx-img-zoom?activeTab=dependencies
