### ISSUE TITLE
Search by packages that have a bin file

### ISSUE THREAD

**Issue by tjbenton** [npm/registry-issue-archive#122]
There's times where I'm looking for a cli tool that's used in the command line and currently they're hard to find because there's so many packages that don't have a bin file. Also on the other hand I've tried searching for a cli tool that I want to help build my cli or help test my cli and not packages that are used through the command line only. It would be really nice to have a filter option to make searching for packages easier.

**Comment by zeke** [comment]
This might help a little: https://github.com/nice-registry/cli-packages

> Names of all npm packages that have a command-line interface. Sorted by download count, descending.

**Comment by bcoe** [comment]
Hey @tjbenton, I like this idea 👍 @chrisdickinson has brought up somewhat related ideas of adding additional sorting/searching capabilities around package size, etc.

we're using the open-source npms.io project for our search now, would you mind opening a feature request here:

https://github.com/npms-io/npms/issues
