### ISSUE TITLE
data inconsistent

### ISSUE THREAD

**Issue by xsbchen** [npm/registry-issue-archive#128]
the data from https://replicate.npmjs.com is inconsistent with https://registry.npmjs.com.

from https://registry.npmjs.com/wegame-element:
```
"_id": "wegame-element",
"_rev": "11-a754b83bb92196a721f48a1b08deecf8",
"name": "wegame-element",
"description": "A Component Library for Vue.js(fork from https://github.com/ElemeFE/element).",
"dist-tags": {
"latest": "0.1.10"
},
```

from https://replicate.npmjs.com/wegame-element:
```
"_id": "wegame-element",
"_rev": "9-0a8e4a33966a11f842c78d6e8f2fba11",
"name": "wegame-element",
"description": "A Component Library for Vue.js(fork from https://github.com/ElemeFE/element).",
"dist-tags": {
"latest": "0.1.8"
},
```

**Comment by soldair** [comment]
replicate can run behind the production registry a little bit. We have alerts to make sure its never very long but in some cases in the past its taken a while to resolve. Things look good now though.
