### ISSUE TITLE
/-/all/static/today.json API won't contains public scope package

### ISSUE THREAD

**Issue by fengmk2** [npm/registry-issue-archive#13]
Like `@angular/platform-server` package was published today, but I can't found it on http://registry.npmjs.org/-/all/static/today.json .

**Comment by soldair** [comment]
yes. scoped modules do not appear.
this is intentional for now because we need to do more work on the infrastructure to make sure private scoped modules stay private.

**Comment by fengmk2** [comment]
But this scoped package is public https://www.npmjs.com/package/@angular/platform-server

**Comment by soldair** [comment]
i understand 
The issue is we need to check every scoped module permissions every time we include it in a feed like this. Its going to get done but its a feature that is not complete. This feature also may only be available through the new api. 

if you need to access them you can https request for scoped json that 404s like a caching proxy.

**Comment by fengmk2** [comment]
OK, I see.

When the new api will be ready? Because we need this feature to sync published packages on mirror. Without it, the public scoped packages will be alway missing.

**Comment by soldair** [comment]
i dont have a date yet. 
i recommend using the cli api for fetching package json for scoped modules. this is not going away because the cli uses it. If you do this the scoped packages will not be missing. because you would request the json from a registry that supports scopes when you encounter one.

**Comment by soldair** [comment]
ill update when i have good news for you though :smile:

**Comment by fengmk2** [comment]
Yep, I use `/-/all/static/today.json` API to find out which packages was updated today. Without this feature, I can't know which scoped package's names are update, so I can't sync them.

**Comment by fengmk2** [comment]
@soldair 

I'm running a npm registry mirror(https://npm.taobao.org) in China, can I get the hook(https://github.com/npm/registry/pull/22) for all public packages?

**Comment by soldair** [comment]
Not really. You could use it to replicate specific scopes.

The scoped module changes feed is almost ready. Which is not exactly
all.json but its the official way to replicate the registry.  probably 1-2
weeks at the most.

We may start to build the cli search json you use with this feed. If we do
you won't have to change anything. I don't have a date for that feature
though.

**Comment by fengmk2** [comment]
> The scoped module changes feed is almost ready.

OK, The scoped module changes feed will satisfy like `today.json` feed for me.

**Comment by soldair** [comment]
hey you can use this changes feed now =) https://replicate.npmjs.com/

**Comment by fengmk2** [comment]
OK, I will try https://replicate.npmjs.com/-/all/static/today.json now.

**Comment by soldair** [comment]
i dont think that will work. use the module changes-stream please =)

**Comment by fengmk2** [comment]
I get it

```
curl -v 'https://replicate.npmjs.com/_changes?since=2607000'
*   Trying 52.26.171.82...
* Connected to replicate.npmjs.com (52.26.171.82) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.npmjs.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /_changes?since=2607000 HTTP/1.1
> Host: replicate.npmjs.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: scoped-replication-endpoint/0.0.0 (like CouchDB)
< Date: Thu, 23 Jun 2016 20:12:25 GMT
< Transfer-Encoding: chunked
< 
{"seq":2607001,"id":"expressions-js","changes":[{"rev":"7-b086004ab409ff117b6f40ad8c475990"}]}
{"seq":2607005,"id":"nflow-devtools","changes":[{"rev":"7-2dfa63a82e0dad4dd8e198539d2aa223"}]}
{"seq":2607006,"id":"rollup-plugin-json","changes":[{"rev":"3-51014c5d0f6d730359cbbae55cf23c43"}]}
{"seq":2607011,"id":"rollup-plugin-node-resolve","changes":[{"rev":"5-ae17d17dd97a3e93dce95960034e7f43"}]}
```

**Comment by fengmk2** [comment]
@soldair Thanks a lot!

**Comment by gziskind** [comment]
How does this differ from the changes feed on https://skimdb.npmjs.com/registry/_changes? Because i am used to accessing this with https://skimdb.npmjs.com/registry/_changes?since='sequence-number' but with replicate.npmjs.com, i am getting different results

**Comment by marob** [comment]
As the issue's title suggests, it includes public scope packages as well (which aren't included in skimdb).

**Comment by gziskind** [comment]
I meant how does the format of the contents returned differ, not the fact that it includes public scoped packages. Previously i was getting a JSON object with a results field, but in the replicate.npmjs.com it seems to be giving me a continuous feed of information rather than a single document

**Comment by ashleygwilliams** [comment]
both are a changes feed- so both give a continuous feed unless you tell it to stop. do you have an example @gziskind ? i've worked extensively with both and see no change but the one @marob mentioned.

**Comment by gziskind** [comment]
Sure. If i request https://skimdb.npmjs.com/registry/_changes?since=318497 i get the results after sequence 318497 in a discrete document

```
{
results: [
  {seq: 318498,id: "fortressjs-naked",changes: [{rev: "2-754555e5b22ee6bb1f88c631f134b68e"}]},
  {seq: 318499, id: "hygienist-middleware",changes: [{rev: "4-02ef067fb12af54bc21671dc396481fc"}]}
],
last_seq: 318499
}
```

But i when i request a simliar document on replicate.npmjs.com i just get a feed that stays open and continues to give me changes on the same request ex) https://replicate.npmjs.com/_changes?since=2891975

```
{"seq":2891976,"id":"requirement-saga","changes":[{"rev":"4-728f4fe72ce045fc1c4bb0704a687d69"}]}
{"seq":2891977,"id":"ecmarkup","changes":[{"rev":"63-3c8527edc70d731b40cbe7187123036c"}]}
{"seq":2891981,"id":"covutils","changes":[{"rev":"26-e1cf2a7b1a1a0a37dd8e4c2dc41e7d95"}]}
{"seq":2891982,"id":"fat-nuka-carousel","changes":[{"rev":"1-be1b0465be67d654e41f9da55506bf1c"}]}
...
```

It seems as if the default feed type switched to continuous

**Comment by marob** [comment]
I would say that https://replicate.npmjs.com/_changes?since=2891975 is the equivalent of https://skimdb.npmjs.com/registry/_changes?since=318497&feed=continuous (but with scope packages).

Note the "feed=continuous" query param.

**Comment by gziskind** [comment]
yes i know that. 

i guess the base of my question is now, am I able to get the new replicate feed to return results in a non continous feed similar to the default for the previous feed?

**Comment by ashleygwilliams** [comment]
hey @gziskind i'm chatting with the team about this right now, but as a stop gap you can just check that you reached the change that you wanted and then stop the feed, a la https://github.com/npm/readme-tester/blob/master/index.js#L33. and in the meantime, i'm working to see if there's a better solution.

**Comment by ashleygwilliams** [comment]
following up @gziskind -- it does look like `feed=continuous` is currently in the source. our goal is to replicate  couchdb's api as faithfully as possible- we're in a period of soft launch- so pointing out these discrepancies is Super Helpful. so thank you! and we'll update you when we've fixed this.

**Comment by bushong1** [comment]
@ashleygwilliams is there an open issue anywhere to track this?

**Comment by gziskind** [comment]
@ashleygwilliams any status on this fix?

**Comment by soldair** [comment]
@gziskind no updates at this time. sadly this has not bubbled to the top of our priority list again

**Comment by bushong1** [comment]
@soldair can we have this issue reopened then?

**Comment by gziskind** [comment]
A new issue was opened #60, but it looks like its already been implemented. Great news

**Comment by soldair** [comment]
yeah. sorry for not commenting here but its totally been resolved for weeks and i just found out! =)
