### ISSUE TITLE
Unable to get information for specific version from registry

### ISSUE THREAD

**Issue by rosen-vladimirov** [npm/registry-issue-archive#130]
Hi, 
Previously we've been using the following URL in order to get information for specific package version:
`http://registry.npmjs.org/<package_name>?version=<version>`
However it does not work anymore? Is there a particular reason?
Some examples:
```
http://registry.npmjs.org/rosen-test-npm-package?version=1.0.0
http://registry.npmjs.org/@angular%2fcore?version=2.4.8
```
Now the query parameter is disregarded and the result contains the full information for the package.

We've tried to workaround this by changing the URL to:
`http://registry.npmjs.org/<package_name>/<version>`
However this introduced other issues - we are not able to get information for scoped dependencies - for example the following requests return 401 with ERROR in the headers: `ERROR: you cannot fetch versions for scoped packages`:
```
http://registry.npmjs.org/@angular%2fcore/latest
http://registry.npmjs.org/@angular%2fcore/2.4.8
```
Interestingly this one works:
```
http://registry.npmjs.org/@angular%2fcore/next
```

Can you please assists us - we need to get information for specific version only. I know that we can parse the JSON returned by `http://registry.npmjs.org/<package_name>`, but it's easier for us to get info for specific version only.

**Comment by ashleygwilliams** [comment]
hi @rosen-vladimirov! thanks for filing and sorry you are dealing with this. you are correct that the API behavior changed! but that was a bug. we have a PR open to fix it and you should see the old behavior return soon. sorry for the extended delay in reply and thank you for your patience.

**Comment by rosen-vladimirov** [comment]
Hey @ashleygwilliams ,
Thanks for the information. I'm glad the issue will be fixed.
