### ISSUE TITLE
NPM registry is truncating JSON response for -/all

### ISSUE THREAD

**Issue by billti** [npm/registry-issue-archive#132]
_Reporting here per suggestion on https://github.com/npm/npm/issues/15865_

#### What's going wrong?
The Node.js Tools for Visual Studio download a copy of the registry from https://registry.npmjs.org/-/all to provide a local search experience. (I know this endpoint is going away, but we haven't updated yet, and existing installs will still use it).

As can be seen at https://github.com/Microsoft/nodejstools/issues/1481 , a number of users have started hitting issues with downloading/refreshing the list of packages. Debugging through this, I can see that a truncated response is being returned, thus resulting in invalid JSON.

This can also be seen easily in the Chrome Dev Tools per the screen shot below. Notice the content-length shown (the actual registry is over 200MB now I believe). Saving the resulting response and inspecting you'll also notice the truncated contents, which make parsing the JSON fail.

![registry](https://cloud.githubusercontent.com/assets/993909/23324250/873084ee-faa1-11e6-98cb-6e1e5d61655a.png)

#### How can the team reproduce the problem?
Just using the Chrome browser/Dev Tools (or Curl) should reproduce the problem.

**Comment by billti** [comment]
ping... any update on this issue (or confirmation of it being an issue on your end)?

**Comment by soldair** [comment]
i dont believe we've been able to reproduce it on our end. but we are looking into it =)
we made no changes to the service so its very mysterious. Our intention is for it to work for the time being.

at the same time have you looked at migrating to the changes stream? this is the best way to process this data generally.

**Comment by emil-eklund** [comment]
Getting the same issue on my end but with a different content-length:
> HTTP/1.1 200 OK
> Server: nginx/1.4.6 (Ubuntu)
> Content-Type: text/plain
> Last-Modified: Fri, 10 Mar 2017 13:43:05 GMT
> ETag: "58c2ad69-a27f000"
> Expires: Fri, 10 Mar 2017 14:43:05 GMT
> Content-Type: application/json
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: GET
> Cache-Control: max-age=3600
> Content-Length: 170389504
> Accept-Ranges: bytes
> Date: Fri, 10 Mar 2017 14:10:16 GMT
> Via: 1.1 varnish
> Connection: keep-alive
> X-Served-By: cache-bma7034-BMA
> X-Cache: HIT
> X-Cache-Hits: 0
> X-Timer: S1489155016.966236,VS0,VE0

**Looking at the response it is clearly truncated:** [...]"license":"BSD-3-Clause","readmeFilename":"READM

**Comment by billti** [comment]
This looks like its working again now. (As reported by our customers, and in my testing). Closing...
