### ISSUE TITLE
How to get all npm modules name?

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/registry-issue-archive#136]
from https://github.com/npm/www/issues/129

<hr/>

I want to get all npm modules name.then I can download them.Because we work offline,sometimes it's not inconvenient to download package then send to offline computer.

**Comment by WebReflection** [comment]
the [API](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md) is quite clear, but the outcome is a 235M file.

I've used this command to download it locally:
```sh
curl -Lo npm.json https://registry.npmjs.org/-/all
```

To work with each entry:
```js
// parse once the whole registry (it will take a while)
const npm = require('./npm.json');

// the list of all published modules (403147)
const modules = Object.keys(npm).filter(
  k => !/^_/.test(k) && 'versions' in npm[k]
);
```

Regards

**Comment by rmg** [comment]
@WebReflection there was a blog post [announcing that `/-/all` is being deprecated](http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint) that went out almost a week before your response :-(

**Comment by WebReflection** [comment]
@rmg I guess I'm so "yesterday" then 🤷‍♂️

**Comment by zeke** [comment]
https://github.com/nice-registry/all-the-package-names is a module that's updated daily. 

See https://github.com/nice-registry/all-the-package-names/blob/336988664034a8220e6dd1d24fbe9795d157eb1f/script/build to get a sense of how it collects all the names.

**Comment by rmg** [comment]
@zeke thanks for chiming in! I was unaware of `nice-registry`. The [all-the-packages](https://github.com/nice-registry/all-the-packages) package looks _particularly_ useful, assuming its download mechanism survives after `/-/all` disappears.

**Comment by zeke** [comment]
> assuming its download mechanism survives

Good catch! It won't survive the deprecation of the API. I've opened an issue: https://github.com/nice-registry/all-the-packages

In the meantime, you can use [package-stream](https://github.com/nice-registry/package-stream) which provides a very similar interface, but it's not offline. Also `package-stream` uses the new replicate.npmjs.com endpoint so it includes scoped packages, e.g. `@user/module`, which skimdb never supported.

**Comment by soldair** [comment]
I recommend using the changes feed from replicate.npmjs.com with a module like changes-stream from npm.  Especially if you want to work with the vanilla documents. The nice registry packages make changes to the structure of the metadata which is nice for some usecases but not all. 

you can filter these events with normalize-registry-metadata to make the documents match exactly what npm serves when you request `https://registry.npmjs.org/<the module>` @rmg
