### ISSUE TITLE
NPM Enterprise is requesting credentials for dist-tags endpoint even when authentication is disabled

### ISSUE THREAD

**Issue by mahikhond** [npm/registry-issue-archive#138]
We are experiencing an unexpected authentication error:

When we try to run `npm dist-tags ls my-package-name`, it gives the following error -
`Error retrieving user data, try logging in again.” with HTTP status code as 500 i.e internal server error.`

**Comment by frvge** [comment]
This is affecting my lerna auto-tagging/versioning ( https://lernajs.io/ ).

**Comment by ashleygwilliams** [comment]
hi @mahikhond and @frvge sorry you are running into this issue! please know that you can also email support@npmjs.com at any time. this issue is very old so i am going to close it. please reach out to support if you still need help!

**Comment by frvge** [comment]
@ashleygwilliams , emailing doesn't provide transparency to others with the same issue. I will see if it's still reproducable.
