### ISSUE TITLE
Search API parameter's default values

### ISSUE THREAD

**Issue by tiagoamaro** [npm/registry-issue-archive#139]
Hello,

First, thank you very much for your awesome work on NPM and everything around it! Amazing!

I was checking the newly created docs for the search API, as I'm trying to paginate through it, and I faced a road block: what are the maximum/minimum values/limits for each parameter? And Default values?

Thanks!

**Comment by aearly** [comment]
I appears the default number of items returned is 20, and the maximum is 250.  For example, this query only returns ~1/3 of Sindre Sorhus's packages: http://registry.npmjs.org/-/v1/search?text=author:sindresorhus&size=1000

**Comment by aearly** [comment]
Clarified in e2dd97e

**Comment by tiagoamaro** [comment]
Thanks @aearly!
