### ISSUE TITLE
`npm owner add` timing out

### ISSUE THREAD

**Issue by othiym23** [npm/registry-issue-archive#14]
Reports and context:
- @davglass's tweet: https://twitter.com/davglass/status/728681870628556800
- https://github.com/npm/npm/issues/12521
- https://github.com/npm/npm/issues/12610

**Comment by piscisaureus** [comment]
`npm access grant read-write ibmcloud:strongloop strong-spawn-npm` -- times out too

**Comment by chrisdickinson** [comment]
This appears to have been due to a PG connection pileup. We bumped the maximum size of our postgres connection pool and this appears to have fixed the problem. We'll continue to monitor this, though!

**Comment by ashleygwilliams** [comment]
hey @chrisdickinson what's the status on this? given we haven't gotten any more comments, perhaps we are good to close this?

**Comment by chrisdickinson** [comment]
Yep! I believe this has been resolved. Thanks all!
