### ISSUE TITLE
503 No healthy backends

### ISSUE THREAD

**Issue by hugodes** [npm/registry-issue-archive#141]
I've been getting this error for the past hour:

> npm http 503 https://registry.npmjs.org/@types%2fexpress
> npm ERR! registry error parsing json
> npm info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
> npm info retry 
> npm info retry <?xml version="1.0" encoding="utf-8"?>
> npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
> npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> npm info retry <html>
> npm info retry   <head>
> npm info retry     <title>503 No healthy backends</title>
> npm info retry   </head>
> npm info retry   <body>
> npm info retry     <h1>Error 503 No healthy backends</h1>
> npm info retry     <p>No healthy backends</p>
> npm info retry     <h3>Guru Mediation:</h3>
> npm info retry     <p>Details: cache-lhr6342-LHR 1489592768 3606632311</p>
> npm info retry     <hr>
> npm info retry     <p>Varnish cache server</p>
> npm info retry   </body>
> npm info retry </html>
> npm info retry 
> npm http 503 https://registry.npmjs.org/@types%2fbluebird
> npm ERR! registry error parsing json
> npm info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
> npm info retry 
> npm info retry <?xml version="1.0" encoding="utf-8"?>
> npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
> npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> npm info retry <html>
> npm info retry   <head>
> npm info retry     <title>503 No healthy backends</title>
> npm info retry   </head>
> npm info retry   <body>
> npm info retry     <h1>Error 503 No healthy backends</h1>
> npm info retry     <p>No healthy backends</p>
> npm info retry     <h3>Guru Mediation:</h3>
> npm info retry     <p>Details: cache-lhr6342-LHR 1489592768 3606632317</p>
> npm info retry     <hr>
> npm info retry     <p>Varnish cache server</p>
> npm info retry   </body>
> npm info retry </html>
> npm info retry 
> npm http 200 https://registry.npmjs.org/validator
> npm info retry fetch attempt 1 at 3:46:08 PM
> npm info attempt registry request try #1 at 3:46:08 PM
> npm http fetch GET https://registry.npmjs.org/validator/-/validator-6.2.1.tgz
> npm http fetch 200 https://registry.npmjs.org/validator/-/validator-6.2.1.tgz
> npm info attempt registry request try #2 at 3:46:18 PM
> npm http request GET https://registry.npmjs.org/@types%2fexpress
> npm info attempt registry request try #2 at 3:46:18 PM
> npm http request GET https://registry.npmjs.org/@types%2fbluebird
> npm http 503 https://registry.npmjs.org/@types%2fexpress
> npm ERR! registry error parsing json
> npm info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
> npm info retry 
> npm info retry <?xml version="1.0" encoding="utf-8"?>
> npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
> npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> npm info retry <html>
> npm info retry   <head>
> npm info retry     <title>503 No healthy backends</title>
> npm info retry   </head>
> npm info retry   <body>
> npm info retry     <h1>Error 503 No healthy backends</h1>
> npm info retry     <p>No healthy backends</p>
> npm info retry     <h3>Guru Mediation:</h3>
> npm info retry     <p>Details: cache-lcy1142-LCY 1489592778 1226956056</p>
> npm info retry     <hr>
> npm info retry     <p>Varnish cache server</p>
> npm info retry   </body>
> npm info retry </html>
> npm info retry 
> npm http 503 https://registry.npmjs.org/@types%2fbluebird
> npm ERR! registry error parsing json
> npm info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
> npm info retry 
> npm info retry <?xml version="1.0" encoding="utf-8"?>
> npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
> npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> npm info retry <html>
> npm info retry   <head>
> npm info retry     <title>503 No healthy backends</title>
> npm info retry   </head>
> npm info retry   <body>
> npm info retry     <h1>Error 503 No healthy backends</h1>
> npm info retry     <p>No healthy backends</p>
> npm info retry     <h3>Guru Mediation:</h3>
> npm info retry     <p>Details: cache-lhr6341-LHR 1489592778 1961767458</p>
> npm info retry     <hr>
> npm info retry     <p>Varnish cache server</p>
> npm info retry   </body>
> npm info retry </html>
> npm info retry 
>

**Comment by ashleygwilliams** [comment]
hi @hugodes ! so sorry you ran into this error. we actually had a minor service issue due to some :fire: nasty bot 🤖  behavior (in the future checkout our status page here: http://status.npmjs.org/incidents/5mbr4c40fx0t). everything should be working now! please file again if you continue to have trouble. and sorry again :(

**Comment by hugodes** [comment]
@ashleygwilliams Thanks for you're response, the thing though, is I checked the status page, and it said "All systems operational", even though I was getting these errors.
