### ISSUE TITLE
npm login to private repo with npm login --scope=@scope --registry="..." passes with wrong password

### ISSUE THREAD

**Issue by mkarvir** [npm/registry-issue-archive#142]
npm login to private repo with npm login --scope=@scope --registry="..." passes with wrong password. I gave a wrong password while logging in and it passed with following output. It should ideally fail.
npm info adduser Authorized user mrinal-karvir
Logged in as mrinal-karvir to scope @scope on ........
npm verb exit [ 0, true ]
npm info ok

**Comment by soldair** [comment]
this is related to npme and we are following up in a supprt ticket :)

**Comment by ashleygwilliams** [comment]
closing as this is/was being addressed via support.
