### ISSUE TITLE
Abbreviated document version seems not accessible

### ISSUE THREAD

**Issue by medikoo** [npm/registry-issue-archive#147]
I follow https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md

And it seems that abbreviated version is no longer returned for requests as:

```
curl -H "Accept: application/vnd.npm.install-v1+json" https://registry.npmjs.org/npm
```

What I get is 720k of data (covering all versions)

**Comment by bcoe** [comment]
@medikoo npm has a lot of versions; I believe that `720k` is the abbreviated document.

The non abbreviated npm document is about 6MB *phew*, so while still somewhat large this document is significantly truncated.

**Comment by medikoo** [comment]
@bcoe it's true that without this header I get 6MB. Still documentation promises that with this header I will receive light response with information about just one version, and that's not true.
While I receive 720k instead of 6MB, it still contains information about all versions (which I don't need)

It would be way lighter than 720k if the response would have format as promised. 

So current state is that either implementation is buggy or document is not accurate promising not adequate result.

**Comment by ashleygwilliams** [comment]
i believe the action item here is to decide whether this is a documentation error or not. @chrisdickinson thoughts?

**Comment by soldair** [comment]
@medikoo we've fixed the version endpoint.
```
curl https://registry.npmjs.org/npm?version=latest
```
gets you the metadata for only a specific version. in this example the current latest tag.

the corgi header `Accept: application/vnd.npm.install-v1+json` reduces the document to only fields npm actually needs to install and always has all versions, but stripped down.

**Comment by medikoo** [comment]
@soldair thanks I'm aware about `version=latest`, still this issue was about something different.

Anyway, it looks that my report is invalid. I got back to document now, and it appears that I misread it.
What's stated as: _`tiny-tarball` is a small package with only one version and no dependencies_
I possibly loosely understood as:  _response contains only one version and no dependencies info_.

I'm closing it. Sorry for confusion
