### ISSUE TITLE
Can't unpublish scoped packages

### ISSUE THREAD

**Issue by watilde** [npm/registry-issue-archive#15]
Hi registry wombats 👋😆

I couldn't unpublish my scoped packages so far when I did publish them once without `--acess=public` and payment information as well, in spite of I registered payment information later.

Reproduce steps:

```
$ node -v
v5.5.0
$ npm -v
3.8.9
$ npm adduser
// ^login as a user who don't register payment information yet
$ mkdir test && cd test
$ npm init --scope=@watilde --yes
// ^should be your name
$ npm publish
```

Then you can't unpublish the package. I could only remove versions correctly:

```
$ npm unpublish @watilde/testtest@1.0.0
$ npm unpublish @watilde/testtest@1.0.1
```

, but eventually I still can not do anything on the empty module, you can see it 👉 [@watilde/testtest](https://www.npmjs.com/package/@watilde/testtest)
<img width="1235" alt="screen shot 2016-05-09 at 13 48 09" src="https://cloud.githubusercontent.com/assets/1716463/15112217/f7b9d5f2-15ec-11e6-8539-474d3678f3d9.png">

Related issue(in Japanese): https://github.com/watilde/npm/issues/13

Let me know if you need more information. Thanks!

**Comment by chrisdickinson** [comment]
Hi! Thanks for the report. Indeed there was a bug where one could publish a private package without first having a subscription to private packages! As a result of this report, we released a registry fix for this that prevents private package publishes for unpaid accounts on May 23rd. Thanks again, and sorry for the delay.
