### ISSUE TITLE
NPM registry endpoints -/all/static/somename.json are responding empty

### ISSUE THREAD

**Issue by NathanaelA** [npm/registry-issue-archive#150]
https://registry.npmjs.org/-/all/static/today.json  & https://registry.npmjs.org/-/all/static/yesterday.json are returning the majority of the time just `[ ]` occasionally it works and brings the proper json file.

This issue might be related to https://github.com/npm/registry/issues/132 - but 132 is supposedly fixed as of a couple days ago.

For a hack fix, my download script right now currently checks every minute until it gets results back.  So it had to hit the server 6 times this last time before it finally got a non empty array response...  (Fortunately it only does this update once a day)   -- And yes I'm aware this endpoint is going away in the future, but until we have time to get everything updated....

**Comment by soldair** [comment]
sorry you had to work around it thanks for letting us know.

**Comment by fengmk2** [comment]
I got the same problem.

`https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1496196697779` 302 redirect to `https://registry.npmjs.org/-/all/static/yesterday.json`, but `yesterday.json` is empty.

```
$ curl https://registry.npmjs.org/-/all/static/yesterday.json
[

]
```

**Comment by fengmk2** [comment]
@soldair any progress?

**Comment by pombredanne** [comment]
@soldair any update on the status for this? Thanks!

**Comment by soldair** [comment]
these endpoints have been deprecated. 
http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint


if you need to know what things are changed please use a follower to get this information.  they're great
 https://github.com/npm/registry-follower-tutorial

if you only need to know if a few packages have changed or packages by specific scopes consider using webhooks. this post is old. webhooks are now free
http://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm

**Comment by pombredanne** [comment]
@soldair Thanks for the updates but the post you reference states `in six months, on September 1 2017, we plan to shut down the servers that back the GET /-/all endpoint of registry.npmjs.org.` .... As far as I know this is not yet September 2017? And Just to be clear does the registry follower allows to eventually create a complete replica of the metadata?

**Comment by soldair** [comment]
the follower is the only way to create a consistent replica. =)
it also only downloads changes since the last change you saw if you save the sequence ids

its not september 2017 as you point out but i think the service that was already creaking under the sheer number of packages could not continue to be useful. the blog post shows how to make requests though our new search endpoint also if you prefer search to replicating the registry.

**Comment by pombredanne** [comment]
@soldair Thanks for the details. All is clear now!
