### ISSUE TITLE
Improve documentation of "GET·/{package}/{version}"

### ISSUE THREAD

**Issue by medikoo** [npm/registry-issue-archive#151]
It says that:

```
version: a version number
```

While it doesn't say we can use tokens as e.g. `latest`.

I was searching for the way to obtain latest version of package, and after reading the doc I thought the only way is to do `GET·/{package}/` which in all cases gives really verbose responses.

**Comment by medikoo** [comment]
It looks, that probably it's solved with: https://github.com/npm/registry/pull/152 (?)

**Comment by ashleygwilliams** [comment]
closed by #152
