### ISSUE TITLE
The package has been published under different Owner

### ISSUE THREAD

**Issue by larixer** [npm/registry-issue-archive#154]
Hi,

I have published the package 
https://www.npmjs.com/package/webpack-overlay-modules
This was my first attempt to publish anything in npm registry. It was quite surprising that this package have got published under different Owner https://www.npmjs.com/~npahucki whom I don't know at all and who does not have relation to the code of this package. The link to the source code repo is correct https://github.com/sysgears/webpack-overlay-modules. 

I have submitted support request on npmjs.org, but no one replied me. After that I have renamed GitHub repo to:
https://github.com/sysgears/webpack-virtual-modules
and published the package under new name on npm: 
https://www.npmjs.com/package/webpack-virtual-modules
which went fine this time.

I'm still worried however that my code is published on npm registry under
https://github.com/sysgears/webpack-overlay-modules
and I have no control over it. Ideally I would like that webpack-overlay-modules to be deleted. I think no one uses it.

Please advise

**Comment by ashleygwilliams** [comment]
hi @vlasenko ! i am so sorry you ran into this issue, i'm investigating right now!

**Comment by ashleygwilliams** [comment]
ok so we had a pretty serious ops incident on the 30th and i believe that may have affected this. i am gonna make a support request to remove the other package from the registry. i'll let you know when it has been deleted.

**Comment by larixer** [comment]
@ashleygwilliams Thank you for your help Ashley!

**Comment by ashleygwilliams** [comment]
np @vlasenko i've opened a support ticket with you and we'll handle it from there! will close this issue.
