### ISSUE TITLE
registry.npmjs.org/-/all returning empty response

### ISSUE THREAD

**Issue by colelloa** [npm/registry-issue-archive#159]
I'm currently trying to hit https://registry.npmjs.org/-/all but the response has a 200 status message, but nothing in it. Usually, it is a JSON-based list of all packages in NPMjs. Is this API endpoint still being used, and if not is there another API endpoint that can be used to get all packages?
Ran this from Boston, MA at 10:20 AM EST on 4/21/2017:
```Python 3.5.2 (default, Jun 29 2016, 13:43:58)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> resp = requests.get('https://registry.npmjs.org/-/all')
>>> resp
<Response [200]>
>>> resp.text
''
```

**Comment by BenLubar** [comment]
It looks like a caching problem. If I add some gibberish after the URL, like `?abcdefg`, it redirects to `/-/all/static/all.json`, and adding gibberish after that URL gives the type of result `/-/all` used to give.

**Comment by jake-brandt** [comment]
Bumped into this while trying to use the NPM browser of VS2015's Node extensions

**Comment by colelloa** [comment]
issue appears to be getting worse; doing the gibberish that @BenLubar suggested is no longer working

**Comment by colelloa** [comment]
going to go ahead and guess that this issue is related to this: http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint

**Comment by pombredanne** [comment]
@colelloa why close this? the blog post you mentioned stated that these would work until September 2017?

**Comment by colelloa** [comment]
@pombredanne the realization that
 a) this issue will probably not be fixed since the endpoint is getting deprecated within 2 months
 b) the same functionality can be attained at https://skimdb.npmjs.com/registry/_all_docs . i'd classify this as "won't fix" and "workaround issued"

**Comment by pombredanne** [comment]
@colelloa Thanks. I also got more details through #150 ... All set!
