### ISSUE TITLE
Lost control over my own package after create org from name

### ISSUE THREAD

**Issue by steambap** [npm/registry-issue-archive#163]
account name: steambap
prev account name / org name: oc-weilin-shi

I convert my account to an org and then I lost control to all of my package. I can still publish packages, but I'm unable to add new collaborators, add package to a team, etc.

I totally lost control over them after I accidentally delete some randomly named team.

**Comment by aearly** [comment]
Hi @steambap,  please email support@npmjs.com and they will sort it out for you.

**Comment by steambap** [comment]
They fixed my issue. Thank you.
