### ISSUE TITLE
Reserve windows package names

### ISSUE THREAD

**Issue by leipert** [npm/registry-issue-archive#165]
Regarding a bug that appeared in the rust community (https://github.com/rust-lang/crates.io/pull/695 and http://sasheldon.com/blog/2017/05/07/how-i-broke-cargo-for-windows/), should we reserve some package names to mitigate problems?

May be relevant:
https://github.com/npm/policies/issues/36
https://github.com/npm/npm/issues/10833

**Comment by ashleygwilliams** [comment]
hi! thanks for filing this. i will bring it up internally. thanks!
