### ISSUE TITLE
/downloads/point/last-month returns 503 for some packages when grouped

### ISSUE THREAD

**Issue by ChALkeR** [npm/registry-issue-archive#167]
* <https://api.npmjs.org/downloads/point/last-month/koa,pipe> — 503
* <https://api.npmjs.org/downloads/point/last-month/pipe,pipe_> — 503
* <https://api.npmjs.org/downloads/point/last-month/koa,pipe_> — OK
* <https://api.npmjs.org/downloads/point/last-month/pipe> — OK
* <https://api.npmjs.org/downloads/point/last-month/koa> — OK

**Comment by bcoe** [comment]
@ChALkeR this was related to `pipe` and has now been fixed 👍
