### ISSUE TITLE
Intermittent 504's from npm registry

### ISSUE THREAD

**Issue by shaunwarman** [npm/registry-issue-archive#17]
Is there a way to track npm update windows that may cause 504's for incoming requests during that time? We are seeing pockets of 5 to 10 minutes at random where all we receive is 504 from the npm registry. 

Example:

```
16:31:09 npm ERR! argv "node" "/jobvolume/workingcapitalnodeweb-ci-5633/workspace/workingcapitalnodeweb-ci-5633_pullrequest/.nvm/v0.10.44/bin/npm" "install" "buildorch-inc@~0.1.0"
16:31:09 npm ERR! node v0.10.44
16:31:09 npm ERR! npm  v2.15.3
16:31:09 npm ERR! code E504
16:31:09 
16:31:09 npm ERR! Gateway Timeout : shortstop-handlers
16:31:09 npm ERR! 
16:31:09 npm ERR! If you need help, you may report this error at:
16:31:09 npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by soldair** [comment]
we'll look into this now. we are not seeing elevated error rates on our graphs and there should be no service interruption.

**Comment by soldair** [comment]
@shaunwarman could you gist or email me your npm-debug.log from one of these 504 cases?
support@npmjs.com. i was only able to find a handful of 504s all related to routes that don't exist or calls to a tarball that was unpublished a while back. these should not 504 of course just letting you know what i found.

With your debug log i can see how long it took to timeout and verify how for the requests made it internally before getting stuck.

**Comment by shaunwarman** [comment]
@soldair Sorry for the late response. I am trying to get an `npm-debug.log` from the machines before the CI workspace is cleaned up. We had another occurrence at 12:05 CST.

The issue was almost immediately resolved by about 12:07 or 12:08. I would say we saw about 10k `502` or `504`'s.

**Comment by shaunwarman** [comment]
Seeing another spike today at 12:06 CST. Ironically, 12:06ish seems like the magic time.

Any updates on your side recently?

**Comment by soldair** [comment]
no changes at all. =/
i think its important to figure out a way to get these logs. and even better stats-npm logs for these failed builds.

is there a way you can mv the files out of the build directory before it cleans up?

**Comment by shaunwarman** [comment]
Hmm, seems stable recently. Not entirely sure 😕
