### ISSUE TITLE
[Enterprise]Unable to hit nodesecurity/npm from inside the Docker container due to proxy server settings.

### ISSUE THREAD

**Issue by ritsingh** [npm/registry-issue-archive#173]
It seems that the docker container is ignoring the proxy server settings. It can’t locate the curl nodesecurity/npm.

The proxy server settings are defined in the Admin settings page.

**Comment by ashleygwilliams** [comment]
hi! could you please reach out to support@npmjs.com. solving this will require some back and forth and more details so i think it's best that you work directly with our npme support team. i'll be closing this- they are very responsive and should be able to help.
