### ISSUE TITLE
lodash._basetostring not reporting 4.12.0 as latest.

### ISSUE THREAD

**Issue by jdalton** [npm/registry-issue-archive#18]
Some folks are seeing issues (https://github.com/lodash/lodash/issues/2326 and https://github.com/npm/npm/issues/12680)
with [lodash._basetostring](https://www.npmjs.com/package/lodash._basetostring) not reporting 4.12.0+ as its latest.

**Comment by constancecchen** [comment]
This is blocking our AWS Elastic Beanstalk deploy. 😢 Is there any chance of an ETA? Or does anyone possibly have a workaround for deploying to EB from a degraded instance without doing a full npm install?

**Comment by vbotnaru** [comment]
must be a proxy issue. went home and everything works just fine.

**Comment by Frizi** [comment]
Was failing for me when registry in .npmrc was set to nexus proxy. Works fine with direct connection.

**Comment by soldair** [comment]
interesting. thanks for figuring this out. 
@constancecchen are you configured to use some kind of proxy as well? We could not reproduce yesterday from any of our edges or bypassing cdn.

**Comment by jdalton** [comment]
I got [a report](https://github.com/lodash/lodash/issues/2334) of someone hitting this with `lodash._baseiteratee`.

**Comment by soldair** [comment]
we need gists to `npm-debug.log`s whenever folks hit this if they can.
we just need a but more information about when the requests are made, how long they took and where they went to uncover a pattern.

**Comment by mikesusz** [comment]
i observed this last night as well, approx. 4hrs after this issue was opened. i can't recover logs as our Jenkins workspaces are recycled, but i can add that we use an artifactory repo and the artifactory was still reporting 3.0.1 as latest (even after npm cache clean) when the npm registry was saying 4.12.0. this morning our artifactory is reporting 4.12.0, so sometime between ~11pm yesterday and 8am EST today, it updated. i'm digging into the artifactory docs to see what their TTL on cached package info is.

**Comment by soldair** [comment]
ok thanks for the information.
these are the facts as i see them so far based on comments:
- folks using artifactory, nexus, and maybe other proxies have cached older versions of lodash modules.
- this new version was published on 2016-05-12
- the registry is serving the correct versions with appropriate etags and cache headers

for you folks having the issue i suggest using the http://registry.npmjs.org as your registry. 
you can also try npm enterprise or open source mirrors that use the changes feed like local-npm.

**Comment by soldair** [comment]
I'm closing this for now because it seems like it is not a registry issue. 
If folks find some npm-debug.logs that have more information or information to the contrary please please link them here.

**Comment by jdalton** [comment]
> this new version was published 5 days ago

The issue is with the [individual lodash method packages](https://www.npmjs.com/browse/keyword/lodash-modularized) which were published a day ago
(when all the reports started).

**Comment by leslc** [comment]
To add, I saw this yesterday when hitting NPM directly:

https://registry.npmjs.org/lodash._basetostring (latest version shown was 3.0.0)

But glad it's fixed!

**Comment by cee-chen** [comment]
Apologies for the delay. I can confirm that the issue was that our project was using Artifactory, and not pulling directly from npmregistry. Apologies for the confusion and not checking earlier!
