### ISSUE TITLE
Fetching a package field is slower than fetching whole package info

### ISSUE THREAD

**Issue by segrey** [npm/registry-issue-archive#186]
How to reproduce:
1. Fetch whole `grunt` package info:
```
time curl 'http://registry.npmjs.org/grunt'
...
real	0m0.128s
user	0m0.004s
sys	0m0.004s
```

2. Fetch `dist-tags` field for `grunt` package:
```
time curl 'http://registry.npmjs.org/-/package/grunt/dist-tags'
...
real	0m0.884s
user	0m0.004s
sys	0m0.004s
```

Fetching whole package info: 0.128s
Fetching `dist-tags` only: 0.884s

Is there a more effective way to fetch a package field? Fetching whole package info transmits much more data, so I'd like to avoid it if possible. Thanks!

**Comment by soldair** [comment]
maybe you can use the corgi document. its a much smaller version of the packument but with unnecessary fields stripped.

```
curl -H 'Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' https://registry.npmjs.org/lodash
```

the reason field values take longer is we dont cache them as static files and its unlikely for them to be in cdn cache. you should pretty much always pull the full document instead of generated responses.

also if you can handle gzip that's even better. Just add `-H 'Accept-Encoding: gzip'`

**Comment by segrey** [comment]
Great, thanks for `application/vnd.npm.install-v1+json`.

**Comment by segrey** [comment]
Probably, not related to this issue, but what's the correct url to fetch metadata for a scoped package?
Tried both `https://registry.npmjs.org/@types/mocha` and `https://registry.npmjs.org/%40types%2Fmocha` to no avail. [Docs](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackage) doesn't specify that. Could you please clarify?

**Comment by soldair** [comment]
it seems to only work if you url encode the / as %2f and leave the @ sign.
`https://registry.npmjs.org/@types%2fmocha`

it seems like a bug that it breaks if folks url encode the @. we'll have to work on that.

```js
function packageUrl(name){
  return "https://registry.npmjs.org/"+encodeURIComponent(name).replace(/%40/,'@')
}
```

**Comment by segrey** [comment]
Thanks, I see. Is it safe to use the `packageUrl` method? Will it still work once the bug is fixed and correct url will be `https://registry.npmjs.org/%40types%2Fmocha`?

**Comment by soldair** [comment]
Yeah its safe. We will always support `@` un-encoded as far as i know.
