### ISSUE TITLE
Using npm registry from IDE

### ISSUE THREAD

**Issue by segrey** [npm/registry-issue-archive#188]
Hello,

Recently, JetBrains IDEs (e.g. [WebStorm](https://www.jetbrains.com/webstorm/)) started to send http requests to npm registry to fetch the following info:
* Given a package name prefix, fetch first 10 packages with the prefix. It's used in package name completion in package.json, and in `require` statement.
For this purpose, skimdb.npmjs.com and replicate.npmjs.com are used for unscoped and scoped packages respectively.
For example, https://skimdb.npmjs.com/registry/_design/app/_view/browseAll?group_level=2&skip=0&limit=10&start_key=%5B%22kar%22%5D&end_key=%5B%22karz%22%2C%7B%7D%5D to fetch first 10 packages with `kar` prefix.

* Fetch `dist-tags` for a given package (discussed in https://github.com/npm/registry/issues/186).

Sorry for the late announcement. Is there any thing you'd like to improve from the IDE side? For example:
* Do you experience any difficulties with the increased load?
* Should a special HTTP header be added to distinguish requests sent from the IDE?

**Comment by soldair** [comment]
i think things are fine =)

we have another api for search that might be a better fit for your usecase and faster. https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search

it would be great if you added some identifiable information to the user-agent so we can reach out if there is a problem.

**Comment by segrey** [comment]
Thanks, next major released versions of IDE will set `User-Agent: JetBrains IDE`.
