### ISSUE TITLE
gulp-base 1.1.3 dissapeared

### ISSUE THREAD

**Issue by james-schwartzkopf** [npm/registry-issue-archive#189]
Starting July 3 our CI started complaining that it couldn't find gulp-base@1.1.3

08:50:09 npm ERR! notarget No compatible version found: gulp-base@^1.1.3
08:50:09 npm ERR! notarget Valid install targets:
08:50:09 npm ERR! notarget 0.0.3

This worked on July 2.

Currently it looks like only 0.0.3 is available.  What happened to 1.1.3?

**Comment by Haroenv** [comment]
It’s a deprecated package that was removed: 

> This package is no longer supported and has been deprecated. To avoid malicious use, npm is hanging on to the package name.

see https://www.npmjs.com/package/gulp-base

**Comment by soldair** [comment]
there was a regression for a time to our unpublish blocking logic where folks could unpublish versions that were older than 24 hours. this has been resolved so shouldn't happen to any versions older than 24 hours in the future.
