### ISSUE TITLE
MingGW Windows 7 NPM Login Hangup

### ISSUE THREAD

**Issue by brownrw8** [npm/registry-issue-archive#192]
I noticed when I do `npm login` from MINGW64 prompt it hangs up.  From the Windows 7 System32 prompt (CMD) it works as expected.  Also, the contents of the "Password" field are clearly visible upon entered (unlike CMD).

MINGW64 Behavior:
```
$ npm login
Username: my-user
Password: mypassword
Email: (this IS public) myemail@something.net
Logged in as my-user on https://registry.npmjs.org/.

```
...hangs forever

Windows 7 CMD Behavior:
```
C:\> npm login
Username: my-user
Password: mypassword
Email: (this IS public) myemail@something.net
Logged in as my-user on https://registry.npmjs.org/.

C:\>
```

**Comment by Haroenv** [comment]
This seems like an issue with the cli, so an issue should be opened in https://github.com/npm/npm or sent to support@npmjs.com

**Comment by ashleygwilliams** [comment]
closing as this is a question that should be directed to the CLI repo and/or support.
