### ISSUE TITLE
Error while "npm publish" on existing package

### ISSUE THREAD

**Issue by 3KniGHtcZ** [npm/registry-issue-archive#193]
Hi,
i'm getting PUT 404 while i'm trying to publish new version of existing npm package.

```
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 Not found : @prague-digi/react-shared-components
npm ERR! 404
npm ERR! 404  '@prague-digi/react-shared-components' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Do you have same issues?

**Comment by soldair** [comment]
if you run `npm who` are you logged in as the user who has access to this package? A 404 for a scoped module like this normally means authenticaton failed.

feel free to email support@npmjs.com if you continue to have account/publish issues like this.

**Comment by ashleygwilliams** [comment]
hi! this is likely a problem with your personal setup @3KniGHtcZ. i think that @soldair's answer is a great start but if you continue to have issues i would recommend reaching out to npm support on twitter @npm_support, or via email support@npmjs.com. closing.
