### ISSUE TITLE
Mismatch between search and package info

### ISSUE THREAD

**Issue by akosyakov** [npm/registry-issue-archive#198]
`npm search` as well as https://www.npmjs.com/search?q=@theia/core&page=1&ranking=optimal cannot find a new version of `@theia/core@0.1.1`. But `npm view` and https://www.npmjs.com/package/@theia/core find it.

Should be some caches updated and I should just wait? Or it's a bug?

**Comment by akosyakov** [comment]
What is used to render this page: https://www.npmjs.com/browse/keyword/theia-extension? It seems to work more reliable than `keywords:theia-extension` in the search. I would like to get it programmatically.

**Comment by soldair** [comment]
the search endpoint is delayed 24 hours at this time. Its likely that the delay will go away at some point but it hasnt reached the high enough in the priority list just yet. =(

afaik the endpoint that exposes that data is an internal api only available to the website at this time.

You can

- continue using the search endpoint 

- index yourself with a registry follower. ideal if you need to subscripbe to many many keywords
  - how to make a follower https://github.com/npm/registry-follower-tutorial

- or use npm webhooks!
  - here is a working example of a receiver i made on glitch. https://glitch.com/edit/#!/possible-pipe
  - blog post about webhooks. (they are free to use now) 
http://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm
  - moar docs. https://github.com/npm/registry/blob/master/docs/hooks/endpoints.md
 
from what i can tell adding webhooks to keywords is a completely undocumented feature! so we'll be following up with more docs on that soon. hope this answers your question. feel free to remix the glitch app. you could even set it up to cache and display the last 24 hours of activity to bridge the gap in the search api.

**Comment by soldair** [comment]
the search api andpoint is 
https://api.npmjs.org/search?text=theia-core

https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search

but i believe its also 24 hours delayed.

**Comment by akosyakov** [comment]
@soldair thanks for your explanation!

**Comment by akosyakov** [comment]
@soldair https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion - how can it be used to fetch info for a scoped package?

**Comment by soldair** [comment]
you can't fetch scoped packages by version at this time. You have to fetch the full document and pull the verison you need from the `doc.versions` key. 

On another note the `by version` endpoint should just not be used if you can afford the bytes. It doesnt take advantage of all of the performance work we've invested so much time in to make full package metadata requests fast because its not used by the cli.

you can also request a reduced size document with optional fields like readmes removed if you include an accept header.

```
curl -H 'Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' https://registry.npmjs.com/lodash
```

you can request gzip from this endpoint as well if you would like the may the metadata download size as small as possible.

**Comment by bcoe** [comment]
@akosyakov to query just for your scope, you can do something like this:

`curl -XGET 'https://api.npmjs.org/search?text=scope:theia+filesystem' | json`

we recently rolled out a fix to the issue that was causing brand new modules to take 24 hours to index -- let us know if things are working better or you.
