### ISSUE TITLE
Security notice after malicious packages have been found

### ISSUE THREAD

**Issue by tobmaster** [npm/registry-issue-archive#199]
I've seen this twitter post 
https://twitter.com/o_cee/status/892306836199800836
and the related security issue here
https://snyk.io/vuln/npm:crossenv:20170802

In my opinion it would be good to inform the users of the package when they try to install the package with a warning note about the malicious code and that important information might have been leaked.
 
As it could confuse people wo try to install the package first time, it would be good when at least the site of the package on npmjs.com give a security advise. So that when an install is failing people can find out about the reasons and maybe take necessary actions.

Just removing the package is not enough.

**Comment by soldair** [comment]
hey we released a blog post. I think it answers some of your questions. =)
http://blog.npmjs.org/post/163723642530/crossenv-malware-on-the-npm-registry

**Comment by tobmaster** [comment]
I was clear of the situation but wanted others to get a clear understanding too. 
Good that you added the good writeup.
Maybe you can link to that blog post on the affected sites too? Cause people need to understand the implications. And some might just look for a replacement and dont see the post.
