### ISSUE TITLE
Unable to publish namespaced module

### ISSUE THREAD

**Issue by figadore** [npm/registry-issue-archive#2]
I'm attempting to `npm publish` a package with `"name": "@shinymayhem/binary"`, according to [this article](http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages), but getting the following error

```
npm publish --access=public
npm ERR! publish Failed PUT 402
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "publish" "--access=public"
npm ERR! node v4.2.6
npm ERR! npm  v3.8.0
npm ERR! code E402

npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @shinymayhem/binary
```

The first time I attempted to publish it, I ran into [this issue](https://github.com/npm/npm/issues/12194), but after relogging in, I attempted again, but I forgot `--access=public`, and [this issue](https://github.com/npm/npm/issues/12168) suggests that the package was created with incorrect permissions. 

(npm version 3.8.0)

**Comment by soldair** [comment]
thanks for reporting this. we'll take a look.

**Comment by soldair** [comment]
i cleaned up some buggy records related to the failed first publish. give it a shot and let me know =)

your comment on https://github.com/npm/npm/issues/12194 is correct. if an unpaid user publishes a module for the first time without `--access public` it creates some orphaned records preventing future publishes. Till we can roll out a bug fix we have to fix it for you.

**Comment by soldair** [comment]
ill close this for now because i believe your issue is resolved. please reopen, or create a support ticket by emailing support@npmjs.com if you're still having an issue publishing this module.

**Comment by joshmanders** [comment]
@soldair I ran into this issue yesterday, luckily you got back to me on support email and fixed it. I just found this issue after being told about this repo. Is there any timeline of when this will be fixed? I do not believe I ever attempted to publish the package without `--access public` and still ran into the issue.

Thanks.

**Comment by soldair** [comment]
I don't have an exact time. its on the "soon" pile though.

You may be running into another issues related to auth and your token @joshmanders lets continue via support@npmjs.com

it may help to  `npm logout && npm login` again. i'll need to check the status of your account to help you. If you could attach the npm-debug.log to the support ticket that would help also.

**Comment by joshmanders** [comment]
I haven't pushed on any other packages yet, I had created that account and logged in, attempted to publish with `--access public` and got hit.

**Comment by soldair** [comment]
sounds like a perfect world as far as debugging goes.
sorry you are hitting this though. :/
if you send me the info via support we can get to the bottom of it.

**Comment by ajoslin** [comment]
I'm also experiencing this issue. I sent an email to support with details.

**Comment by kolach** [comment]
same thing. Encouragement to buy a subscription plan?

**Comment by soldair** [comment]
@kolach please send an email to support@npmjs.com with info like your npm-debug.log so we can figure this out.

great @ajoslin. thanks.

**Comment by the-reality-engineer** [comment]
Same problem. I tried to publish a scoped module for the first time.

**Comment by joshmanders** [comment]
Honestly, I don't think private by default is the best thing for scoped modules. I accidentally forgot to put the `--access` flag on a module and now I'm stuck waiting almost 24 hours since submitting a support ticket because by forgetting that flag, that module and version is stuck until they handle it.

**Comment by soldair** [comment]
So sorry for the inconvenience. your publish should have failed without causing any other issues. 

Fixing the partial publish bug makes the default behavior not an issue. I'm certain we'll have the underlying issue fixed soon.

**Comment by joshmanders** [comment]
``` sh
npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @vulcan/registry
```

**Comment by soldair** [comment]
I'm not sure of the question exactly so pardon me if I'm misinterpreting. Do you think this would be better if the error message was reworded to describe how to publish this module as public? Instead of assuming private.

**Comment by joshmanders** [comment]
Well I now know about the ability to do `npm config set access public` so I no longer need to do `npm publish @me/module --access public` all the time, but I just dont understand that when I accidentally forget to set the access to public and I try to publish a module, not only is it denied because I do not have a paid account, now I can no longer publish that version of the module even with `--access public` set again. It should just throw the error and force a re-publish attempt.

**Comment by ashleygwilliams** [comment]
hi @joshmanders i just confirmed the issue of the 403 somehow preventing publishing to the same version. this is unrelated to this issue however, so i will refile and tag you.

**Comment by joshmanders** [comment]
Awesome, thank you Ashley. Lets figure this out and get it fixed. :)

**Comment by soldair** [comment]
> but I just dont understand that when I accidentally forget to set the access to public and I try to publish a module, not only is it denied because I do not have a paid account, now I can no longer publish that version of the module even with --access public set again.

this describes part of the bug we are working on perfectly. It should have failed to publish altogether. instead it partially published preventing you from publishing the module as public. we are working on this.

**Comment by ashleygwilliams** [comment]
@soldair @joshmanders not sure if it is helpful but i filed at: https://github.com/npm/registry/issues/12

**Comment by VinSpee** [comment]
Hi! I just sent an email into support - I think I hit this exact issue.
