### ISSUE TITLE
Two factor authentication for publish / login

### ISSUE THREAD

**Issue by bdharrington7** [npm/registry-issue-archive#200]
Since the [recent](https://twitter.com/o_cee/status/892306836199800836) [discovery](https://www.theregister.co.uk/2017/08/02/typosquatting_npm/) of malicious packages in the npm registry, security was once again hoisted into the spotlight. 

Requests for 2FA on npm is a feature that has been requested and / or mentioned as a solution several times:
https://github.com/npm/npm/issues/17408
https://github.com/npm/npm/issues/10770
https://news.ycombinator.com/item?id=11364453
https://news.ycombinator.com/item?id=11341145

Several security holes would be solved with 2FA:
[ChALkeR on weak credentials](https://github.com/ChALkeR/notes/blob/master/Gathering-weak-npm-credentials.md)
[npm worm vulnerability](https://www.kb.cert.org/vuls/id/319816) [(Article)](http://news.softpedia.com/news/node-js-package-manager-vulnerable-to-malicious-worm-packages-502216.shtml)

Discussions were [started](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) back in early 2016, but haven't been mentioned again until [this month](http://blog.npmjs.org/post/163676667652/securing-the-npm-registry)

To cite a recent scenario that could be npm, and to highlight the need for a 2FA solution for npm, look to what happened on the chrome web store when plugin authors didn't use a feature like this:
https://arstechnica.com/information-technology/2017/08/after-phishing-attacks-chrome-extensions-push-adware-to-millions/

Please consider moving a feature like this to a higher priority for the sake of the nodeJS community's safety.

**Comment by soldair** [comment]
We've been working on this for a while and we all hope it will be ready soon.
we'll announce when it is =)

**Comment by kmoe** [comment]
Why was this issue closed? As far as I can tell, it hasn't been fixed and isn't a duplicate.

**Comment by bdharrington7** [comment]
Ultimately it’s up to the maintainers how they triage issues, but I agree it should not be closed, as it’s a feature still under development. Leaving it open makes the issue easier to find, reducing potential duplicates, and gives visibility into what the team is working on vs. what’s done.

If it’s being worked on, is there an internal issue board being used?

**Comment by soldair** [comment]
I closed this issue because this is not where the registry team tracks ongoing work, and the question was answered. 

@bdharrington7 asked if we would consider making this a higher priority and i let them know we absolutely are.

We do not normally do feature announcements through issue comments. Its just not a very good medium for a thing you need the whole community to know about. Perhaps instead of closing issues like this we can move to a more detailed label system in the future. I'll bring it up internally.

**Comment by aearly** [comment]
2FA is here!  Read all about it: http://blog.npmjs.org/post/166039777883/protect-your-npm-account-with-two-factor
