### ISSUE TITLE
Failed to PUT to registry with 500

### ISSUE THREAD

**Issue by chrisdarroch** [npm/registry-issue-archive#201]
I ran in to this problem on 07-Aug-2017 at 17:55:45 GMT+2.

```
./node_modules/.bin/npm-publish --npmuser atlassian-aui --npmemail aui-team@atlassian.com

info attempt registry request try #1 at 5:55:45 PM
http request GET https://registry.npmjs.org/-/package/@atlassian%2faui/dist-tags
http 200 https://registry.npmjs.org/-/package/@atlassian%2faui/dist-tags
trying to publish to npm
info attempt registry request try #1 at 5:55:46 PM
http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:atlassian-aui
http 201 https://registry.npmjs.org/-/user/org.couchdb.user:atlassian-aui
info attempt registry request try #1 at 5:55:46 PM
http request PUT https://registry.npmjs.org/@atlassian%2faui
http 500 https://registry.npmjs.org/@atlassian%2faui
info retry will retry, error on last attempt: Error: {"code":"InternalError","message":"self.s3Client.client.delFile is not a function"} : @atlassian/aui
info attempt registry request try #2 at 5:56:01 PM
http request PUT https://registry.npmjs.org/@atlassian%2faui
http 500 https://registry.npmjs.org/@atlassian%2faui
info retry will retry, error on last attempt: Error: {"code":"InternalError","message":"self.s3Client.client.delFile is not a function"} : @atlassian/aui
info attempt registry request try #3 at 5:57:05 PM
http request PUT https://registry.npmjs.org/@atlassian%2faui
http 500 https://registry.npmjs.org/@atlassian%2faui
ERR! publish Failed PUT 500
{ Error: {"code":"InternalError","message":"self.s3Client.client.delFile is not a function"} : @atlassian/aui
    at RegClient.<anonymous> (<<build-dir>>/node_modules/npm-registry-client/lib/request.js:247:14)
    at Request._callback (<<build-dir>>/node_modules/npm-registry-client/lib/request.js:170:14)
    at Request.self.callback (<<build-dir>>/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (<<build-dir>>/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (<<build-dir>>/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16) pkgid: '@atlassian/aui', statusCode: 500, code: 'E500' }
<<build-dir>>/node_modules/ci-npm-publish/index.js:66
          throw err
          ^

Error: {"code":"InternalError","message":"self.s3Client.client.delFile is not a function"} : @atlassian/aui
    at RegClient.<anonymous> (<<build-dir>>/node_modules/npm-registry-client/lib/request.js:247:14)
    at Request._callback (<<build-dir>>/node_modules/npm-registry-client/lib/request.js:170:14)
    at Request.self.callback (<<build-dir>>/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (<<build-dir>>/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (<<build-dir>>/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
```

* NPM version 3.10.10
* Node version 6.11.1

I had thought it was an authentication problem (e.g., the same issue as https://github.com/npm/npm/issues/6669), but I can log in to the registry just fine. It could be a problem with an older version of `npm-registry-client` (we're using 6.5.1), but the HTTP 500 from npmjs.com makes me think it's a server-side problem.

**Comment by soldair** [comment]
it looks like the shasum of the tarball in the PUT document doesnt match the shasum of the tarball that was uploaded.

is this consistent or intermittent? only this package? what is `ci-npm-publish`? does it work when you use the npm cli instead of this other package?

**Comment by chrisdarroch** [comment]
Thanks for the response @soldair! 

Some more info:

* This problem is consistent.
* I'm not sure if it occurs for other packages yet.
* The command is being run in a CI environment.
    * Specifically, from Atlassian Bamboo on a Ubuntu 12.04 agent.
    * The agent has an `~/.npmrc` file with registry tokens.
    * The details in the `~/.npmrc` file are for a private registry, not for npmjs.com.
* The build pushes to multiple registries -- our private registry + npmjs.com.
    * Publishing to the private registry works fine ... but we do that via the normal `npm publish` command.
    * The `ci-npm-publish` package is what we use to provide our credentials for npmjs.com in CI.
        * It calls out to `npm-registry-client` under the hood -- specifically to [`RegClient#publish`][1] and [`RegClient#distTags.fetch`][2].

I'll see if I can figure out what shasums are at play here and get back to you. It could be as simple as the usage of `npm-registry-client` isn't providing the required metadata when it makes its request. Or, perhaps some of the data from `.npmrc` is getting involved as well?

[1]:  https://github.com/npm/npm-registry-client#clientdisttagsfetchuri-params-cb
[2]: https://github.com/npm/npm-registry-client#clientpublishuri-params-cb
[3]: https://github.com/npm/npm-registry-client/pull/157

**Comment by soldair** [comment]
have you tried to publish with the cli by passing the --registry flag to https://registry.npmjs.org

`npm publish --registry https://registry.npmjs.org`

npm automatically looks for authentication associated with the selected registry

`npm login --registry https://registry.npmjs.org` will put the  token for the main registry in your cis npmrc.

you can also put the token for the public registry directly in your npmrc with something like this if you already know the token.
`//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000`

**Comment by chrisdarroch** [comment]
The standard `npm publish --registry https://registry.npmjs.org` doesn't work, sadly; it seems the `.npmrc` file on the build agent includes a few lines that ultimately make npm 3.10.10's publish command ignore the `--registry` command.

```
registry=https://private-rego.io/
@atlassian:registry=https://scoped.private-rego.io/
//scoped.private-rego.io/:_authToken=...
```

When the `npm publish` command runs, I just see it pushing to `https://scoped.private-rego.io`. Kinda odd. Perhaps that behaviour is different in the latest npm... so I guess I'll try bumping to npm 5.3.0 on the agent and seeing if that helps at all.

Our CI stores the npmjs registry account's details, which is sub-optimal; I can't run `npm adduser` via CI since it's an interactive prompt.

I'm hunting down the credentials so I can retrieve the auth key and add it to the `~/.npmrc` file manually... though I suspect what I'll actually need to do is *replace* that file with one that points the scoped package to the public registry. That, or I need to figure out what's wrong with the usage of `npm-registry-client` and fix that problem.

**Comment by soldair** [comment]
oh. if the module you want to publish is scoped, and you have config in .npmrc for that scope. You have to override the registry for the scope not the default registry config option.

```
npm publish --@atlassian:registry=https://registry.npmjs.org
```

**Comment by chrisdarroch** [comment]
Well, I'm at an impasse right now.

I don't have access to the auth_token for the account I'm pushing to npmjs.com through, which means that any `npm publish` command is doomed to fail.

I cannot adequately debug the problem in CI. After setting an env variable of `NODE_DEBUG=npm,request,ci-npm-publish,npm-registry-client`, I'm not seeing any information to do with a shasum or anything I could deem useful to figuring out the root cause. I don't understand the exchange that `npm publish` does with the registry, so I don't know what I'm looking for.

:\

Maybe I'll get access to the account within a few days, and can attempt to do the publish via the typical binary. Kinda irritating that there's just a dead end along the other route.

**Comment by soldair** [comment]
In order for publish to work with any client even `ci-npm-publish` its going to need to have had access. and i think you do because the publish gets far enough to hit the shasum error.

You can generate a token by running `npm login --scope=@atlassian`  but the existing token has gotta be in an .npmrc somewhere for you to use.

To publish, a registry client packs the tarball, shasums it, and writes the sum to a json object. The tarball and document are then PUT at the registry. When we save the tarball on our side we check to make sure it hasnt been corrupted by verifying the shasum against the shasum in the document you are trying to save. this is the check that's failing on our side.

if you can use the standard npm cli to publish that'd be great ill be able to help debug a little better with the npm-debug.logs generated and such.

**Comment by chrisdarroch** [comment]
Hi @soldair, using `npm set //registry.npmjs.org/:_authToken=...` and `npm publish --@atlassian:registry=https://registry.npmjs.org/` worked.

I've made gists of the logs from our build agent:

* [before][1] (using env vars for username+password; basic auth via `ci-npm-publish`)
* [after][2] (using a valid auth_token and `npm publish`)

In the "before" set, I see some shasum data was captured for the push to our private registry (i.e., via the proper `npm publish` command), but not for the push via the `npm-publish` binary.  I'll therefore assume the problem was somewhere in the (usage of) the older `npm-registry-client` version.

Thanks for your help!

[1]: https://gist.github.com/chrisdarroch/8001afdac6431be6ece8e9816a298dd1#file-before___with_ci-npm-publish___build-output-log
[2]: https://gist.github.com/chrisdarroch/8001afdac6431be6ece8e9816a298dd1#file-after___with_npm_publish___build-output-log
