### ISSUE TITLE
Detect deleted packages

### ISSUE THREAD

**Issue by Haroenv** [npm/registry-issue-archive#203]
I have a replica of the npm registry by using `db.changes` (PouchDB) of `https://replicate.npmjs.com/registry`, combined with `db.allDocs` periodically to get rid of drift, but both of these don’t include deletions of packages as far as I could tell. Would there be a way to have the deleted packages since a certain timestamp, or another strategy that avoids calling the registry for each package we have in our replica to see if it still exists in the main registry. 

Thanks a lot!

**Comment by soldair** [comment]
We dont delete packages or documents ever =). We may remove versions from published packages but that is just a document update.

if you follow the changes feed and we really did delete a document a tombstone record would be sent in the relication stream by couchdb and pouchdb should remove it automatically.

if you want to know about versions that are unpublished to sync a local tarball mirror or something you can compare the versions in "times" to the versions in "versions" deleted versions remain in "times"

note: on some documents the version in versions doesnt match the value in times. use normalize-registry-metadata on the document to correct this.

**Comment by Haroenv** [comment]
Thanks!
