### ISSUE TITLE
Search API - using qualifiers

### ISSUE THREAD

**Issue by cristofp** [npm/registry-issue-archive#204]
I'm GSoC student contributing to open source project: XWiki (www.xwiki.org).
What I'm currently working on is integration with NPM Registry using it's API.

I have a question - how to specify in search request both - text and qualifier?
What I mean:
To search by text 'mathjs' the path is following
registry.npmjs.org/-/v1/search?text=mathjs
To search by qualifier keywords:-documentation:
registry.npmjs.org/-/v1/search?text=keywords:-documentation

How to combine those two requests? (Search for mathjs entires without keyword 'documentation)?

**Comment by k7moorthi** [comment]
+1

Also how to combine 2 or more qualifiers in a single search query?

**Comment by cristofp** [comment]
I already found out on my own. You need to use '+' as delimiter.

30 sie 2017 00:02 "Kesavamoorthi Subramanian" <notifications@github.com>
napisał(a):

**Comment by k7moorthi** [comment]
@krisss2121 

It worked. Thank you!

**Comment by bcoe** [comment]
@k7moorthi @krisss2121 sounds like you got everything working, awesome \o/ feel free to open this back up if you're still bumping into any issues. Also, feel free to let us know if you have any more questions.
