### ISSUE TITLE
package duration in the registry, cache behavior and enterprise world

### ISSUE THREAD

**Issue by MarcLoupias** [npm/registry-issue-archive#205]
Hi there, let's plant the context first.

I work as a frontend consultant in a big country size organization. In that organization, access to the outside world is very limited. For example, it is impossible to clone a github repository nor to reach the npm registry from a developer computer. An [artifactory server](https://www.jfrog.com/artifactory/) has been installed to allow modern frontend development.

A few weeks ago, i have been set on a 2 years old project to help the frontend team in charge. It is a moderate AngularJS project size (around 100K LOC). My mission is to help the team to refactor the project with good practices to process in the end to a migration from AngularJS 1.4.x to the latest Angular release available.

That said, i have started to work on the dev dependencies to fill the technical debt (removing/updating deprecated packages, removing unused gulp task, updating linters, adding linters and pluggins with proper settings, etc ...). When the project have started, the frontend team have frozen the project with `npm shrinkwrap`. Cloning the repo, installing deps, everything was ok.

After some internal network problems, i have ran a `npm cache clean` CLI command. At that time i was heavily changing devDeps so to avoid costly `npm install` when changing branches i have simply cloned another occurrence of the repo and ran `npm install`. 

And boom ! 

2 dependencies appears missing : 
- `toastr@2.1.1`
- `angular-material-data-table@0.8.14`

Artifactory admins said theses dependencies no longer exist on the regular npm registry so artifactory put them out also.

Was stonished. I have just check on my computer at home to be sure they were not bullshiting me and they are not. The packages vanished from npm registry !

I need, i want to understand what happened.

IMHO, removing a dependency from the registry, is the same thing as rewriting a public git history. It's the same thing as rebasing a published branch. It is **FORBIDDEN**.

I cannot find any clue with `npm view` or [npm website](https://www.npmjs.com/) to understand if the packages have been removed by the owners, or if npm removed them by itself for whatever reason.

This is my first concern.

Second concern is about npm cache behavior. The fact is the cache is lying. If i had not cleaned it, i would not find the issue right now. The CI servers are up because they have the old packages in their cache, but if a hard drive have to be changed, or an admin clean the cache, the build jobs will starts failing without any code change. Same if a new developer comes in with a new computer, it will not be able to `npm install` successfully. It is a big problem.

I know that javascript ecosystem is moving very fast and is very young, i know that theses dependencies are easy to update, but in an enterprise context it can be a thing. For example i have the credentials to change everything in the project that is **not** in the `src/` directory. The business development is outsourced in a different team, for contracts reasons i cannot change the deps on the fly nor manage breaking changes in the `src/` directory.

The registry needs to be more consistent with this. I link this story to the [`left-pad` story last year](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm). Not the same magnitude, but the root problem is the same.

A package published in a version MUST stay as is in the registry, for ever.

Second, the npm cache should not lie. The current cache behavior would be ok if the it was impossible to remove a package from the registry, but it is not the case at the moment. So the cache behavior is inconsistent with the registry management policy.

Voilà :)

Have a nice day.

**Comment by soldair** [comment]
Those versions were most likely unpublished due to a bug in the logic that was supposed to prevent version unpublish after the 24 hour window. This has been fixed now :tada: . We are committed to our unpublish policy. Thanks  for sharing your opinion and im sorry for the difficulty.
