### ISSUE TITLE
README Not Detected.

### ISSUE THREAD

**Issue by sudodaksh** [npm/registry-issue-archive#210]
Here's a Screenshot of My Github:

https://prnt.sc/ghqjun

Here's another One from NPM: 

https://prnt.sc/ghqlp7

Here's one from UNPKG (Which Serves NPM Module Files):

https://prnt.sc/ghqlyx

**Comment by Tymski** [comment]
the same is true for my package
Sadly, there is no README!
_Edit: wait a day and it works_

**Comment by sudodaksh** [comment]
We can just "hope" for the NPM team to fix, because previous issues about this said that the readme.md file didn't exist but this time it does, I checked it from UNPKG CDN.

**Comment by sudodaksh** [comment]
This error magically was resolved. Thanks.
