### ISSUE TITLE
Error 503 No healthy backends on registry.npmjs.org

### ISSUE THREAD

**Issue by niranjan94** [npm/registry-issue-archive#214]
**URLs accessed:** 
- https://registry.npmjs.org/
- https://registry.npmjs.org/@types/mongoose/-/mongoose-4.7.21.tgz

**Error:**
```
Error 503 No healthy backends

No healthy backends

Guru Mediation:

Details: cache-sin18032-SIN 1506060977 3219570535

Varnish cache server
```

**Debug info:**
```
$ nslookup registry.npmjs.org

Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
registry.npmjs.org	canonical name = a.sni.fastly.net.
Name:	a.sni.fastly.net
Address: 151.101.8.162
```

**Comment by GongT** [comment]
+1 in singapore

```
Error 503 No healthy backends

No healthy backends

Guru Mediation:

Details: cache-sin18024-SIN 1506061332 1928129528

Varnish cache server
```

https://status.npmjs.org/ say everything is ok.


also
* https://www.npmjs.com/ -> ERR_CONNECTION_CLOSED

**Comment by niranjan94** [comment]
Looks like it works now ... https://registry.npmjs.org

Will close this issue after 60 mins. :)

**Comment by szavrakas** [comment]
We are experiencing the same issue right now. Is there any kind of maintenance going on?

```
Error 503 No healthy backends

No healthy backends

Guru Mediation:

Details: cache-lhr6342-LHR 1506338744 3817967811

Varnish cache server
```

**Comment by niranjan94** [comment]
✅ Seems to be good here in India. 
✅ Seems to be up in Singapore and US too. 

Closing this issue for now.
