### ISSUE TITLE
Using Hooks for private npm registry

### ISSUE THREAD

**Issue by gciluffo** [npm/registry-issue-archive#223]
I am trying to use <a href="https://github.com/npm/registry/blob/master/docs/hooks/endpoints.md">this</a> API to add webhooks to some of my scoped packages in my private npm registry. However, I am running into some authentication issues even when I am providing a token for my registry in the header.

I am doing a simple POST similar to <a href="https://github.com/npm/registry/blob/master/docs/hooks/endpoints.md#post-v1hookshook">this</a> with my registry's token in the header. `Authorization: Bearer {MY_TOKEN}` However, I am getting a 403 response back saying `invalid CSRF token`. 

I have had success with API with public packages on https://registry.npmjs.org but not for my own registry https://npm-registry.mycompany.com. Anyone have this issue?

**Comment by soldair** [comment]
what kind of private registry are you using? afaik only the main npm registry supports webhooks.

**Comment by gciluffo** [comment]
@soldair We are using npm enterprise 
https://npme.npmjs.com/docs/cli/configuration.html

**Comment by soldair** [comment]
this service hasnt been migrated into npm enterprise yet. I've asked internally what our plans are. we intend that enterprise api is the same as the registry generally.

if you need to be notified about changes to your private packages an option is to write a registry follower  https://github.com/npm/registry/blob/master/docs/follower.md
this would point at the couchdb in your enterprise appliance.

if you need to find the differences between an old version and new version you can use https://www.npmjs.com/package/changes-feed-diff on each change in the stream of changes.
