### ISSUE TITLE
Sadly, this package has no readme for datamanager.js

### ISSUE THREAD

**Issue by tangshuang** [npm/registry-issue-archive#239]
Hi, 

I published my library and found readme was not detected on https://www.npmjs.com/package/datamanager.js.
My repo is https://github.com/tangshuang/datamanager.js

npm version is 5.5.1, macOS 10.12.6

Could you please help to check?

**Comment by aearly** [comment]
Try lowercase `README.md`.

**Comment by tangshuang** [comment]
fixed
