### ISSUE TITLE
412 Precondition Failed

### ISSUE THREAD

**Issue by jmdarr** [npm/registry-issue-archive#246]
Hello! I am one of a team of people that manage an Artifactory instance and am having an issue pulling public packages:

> [jdarr@abox ~]$ curl https://registry.npmjs.org
> 
> <?xml version="1.0" encoding="utf-8"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html>
>   <head>
>     <title>412 Precondition Failed</title>
>   </head>
>   <body>
>     <h1>Error 412 Precondition Failed</h1>
>     <p>Precondition Failed</p>
>     <h3>Guru Mediation:</h3>
>     <p>Details: cache-lax8631-LAX 1511901176 856734217</p>
>     <hr>
>     <p>Varnish cache server</p>
>   </body>
> </html>

Looking at https://github.com/npm/registry/issues/219, it appears that my cluster may have been blocked. Could you check to see if you've blocked 68.178.213.160? If you have not, let me know and I can investigate a NAT IP or individual IPs for each of the boxes behind this cluster.

**Comment by chrisdickinson** [comment]
Hi @jmdarr!

I believe we blocked the cluster this morning after seeing a high volume of HEAD requests. I've removed the block, though, so you should be good to go! Sorry for the trouble — I'll leave this issue open until you confirm that you are unblocked.

**Comment by jmdarr** [comment]
Hey Chris, thanks for looking into this. Here's my new test:

> [jdarr@abox ~]$ curl https://registry.npmjs.org
> {"db_name":"registry","doc_count":726409,"doc_del_count":344,"update_seq":6127857,"purge_seq":0,"compact_running":false,"disk_size":5512720518,"data_size":3637890982,"instance_start_time":"1511889367110308","disk_format_version":6,"committed_update_seq":6127857}

Looks good from my end. Considering this is a large cluster that all of our devs use pointing upstream to you guys for publicly published NPM packages, is there anything I can do to prevent this from getting blocked again?

**Comment by chrisdickinson** [comment]
@jmdarr You should be all good on our end! We'll record the IP we blocked in a "do not block" list internally. Sorry again for the trouble!
