### ISSUE TITLE
package with maximum semver version returns 404 even though it is installable

### ISSUE THREAD

**Issue by michaelficarra** [npm/registry-issue-archive#253]
The `n-pm` package exists and is installable. You can see for yourself that it exists with `npm info n-pm`. But https://www.npmjs.com/package/n-pm returns a 404. The fact that the package's version is the maximum allowed by semver may have something to do with it. See [a tweet from the package author](https://twitter.com/ianh_/status/916077905565777920) for context.

**Comment by silkentrance** [comment]
@michaelficarra this might also have to do with you reusing the 'npm' package name, sort of.

**Comment by silkentrance** [comment]
@michaelficarra this might have been fixed, searching for and navigating to 'n-pm' does work, see for yourself: https://www.npmjs.com/package/n-pm

**Comment by michaelficarra** [comment]
Yep, looks like it's been fixed. Probably with the recent website rewrite.
