### ISSUE TITLE
How can I get a full clone of registry.npmjs.com

### ISSUE THREAD

**Issue by jasonxia23** [npm/registry-issue-archive#254]
I used skimdb to do some statistics, but `doc_count` in skimdb is only 561407, which is far smaller than that in 755616 of registry.npmjs.com or registry.yarnpkg.com.

**Comment by soldair** [comment]
yeah. use the changes feed and point it at https://replicate.npmjs.com
this contains public scoped modules where skim doesn't.

**Comment by soldair** [comment]
feel free to reopen or email support if you have any other questions

**Comment by jasonxia23** [comment]
But the `doc_count` is only 610092. What is the remaining package in registry.npmjs.com?

**Comment by soldair** [comment]
private packages.

**Comment by jasonxia23** [comment]
How did yarn get the full clone of the registry? Just curious about this.

**Comment by soldair** [comment]
they dont. they only have the public data from replicate.npmjs.com. i wouldn't hold much stock in the registry.npmjs.org couchdb info responses. we are hardly couchdb on that end of things.

**Comment by nf404** [comment]
test comment
