### ISSUE TITLE
Still experiencing issue #255 (require-from-string not found)

### ISSUE THREAD

**Issue by jyotirmaybanerjee** [npm/registry-issue-archive#261]
Still facing the issue from - https://github.com/npm/registry/issues/255

npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

**Comment by mic159** [comment]
Same here!

Looks like the API is broken: https://registry.npmjs.org/require-from-string
Look at the `versions` object, it only has `2.0.2` in it.

**Comment by jessarcher** [comment]
We're still experiencing the issue as well, but with [gulp-batch](https://www.npmjs.com/package/gulp-batch) - another of floatdrop's packages.

```
197 http fetch GET 200 https://registry.npmjs.org/gulp-batch 61ms
198 silly fetchPackageMetaData error for gulp-batch@^1.0.5 No valid versions available for gulp-batch
...
1358 verbose Linux 4.13.0-21-generic
1359 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1360 verbose node v8.9.4
1361 verbose npm  v5.6.0
1362 error code ENOVERSIONS
1363 error No valid versions available for gulp-batch
```

The registry entry seems to show every version is unpublished: https://registry.npmjs.org/gulp-batch
```json
{
  "_id": "gulp-batch",
  "_rev": "71-2c1ddfcf88e9e0509a6f9f5984f880de",
  "name": "gulp-batch",
  "time": {
    "modified": "2018-01-06T18:36:23.187Z",
    "created": "2014-01-03T09:58:43.256Z",
    "0.0.0": "2014-01-03T09:58:44.955Z",
    "0.0.1": "2014-01-03T10:06:51.515Z",
    "0.0.2": "2014-01-03T11:07:21.130Z",
    "0.0.3": "2014-01-03T12:11:26.723Z",
    "0.0.4": "2014-01-03T12:26:05.432Z",
    "0.0.5": "2014-01-03T13:41:12.780Z",
    "0.0.6": "2014-01-03T14:06:00.439Z",
    "0.0.7": "2014-01-03T14:19:07.836Z",
    "0.1.0": "2014-01-03T14:21:11.691Z",
    "0.2.0": "2014-01-03T14:34:08.709Z",
    "0.2.1": "2014-01-03T16:34:13.341Z",
    "0.2.2": "2014-01-03T18:34:14.443Z",
    "0.2.3": "2014-01-03T21:14:50.758Z",
    "0.2.4": "2014-01-04T10:42:36.498Z",
    "0.2.5": "2014-01-05T20:30:48.445Z",
    "0.3.0": "2014-01-05T21:22:39.177Z",
    "0.3.1": "2014-01-06T18:53:55.437Z",
    "0.3.2": "2014-01-06T19:18:51.594Z",
    "0.3.3": "2014-01-07T02:14:35.401Z",
    "0.4.0": "2014-01-12T07:11:13.997Z",
    "0.4.1": "2014-01-16T09:26:30.554Z",
    "1.0.0": "2014-09-20T15:15:09.276Z",
    "1.0.1": "2014-09-21T15:46:37.021Z",
    "1.0.2": "2014-11-02T09:30:44.333Z",
    "1.0.3": "2014-11-02T17:33:53.203Z",
    "1.0.4": "2014-12-10T13:43:40.105Z",
    "1.0.5": "2015-01-29T04:58:00.218Z",
    "unpublished": {
      "name": "npm",
      "time": "2018-01-06T18:36:23.187Z",
      "tags": {
        "latest": "1.0.5"
      },
      "maintainers": [
        {
          "name": "floatdrop",
          "email": "floatdrop@gmail.com"
        }
      ],
      "versions": [
        "0.0.0",
        "0.0.1",
        "0.0.2",
        "0.0.3",
        "0.0.4",
        "0.0.5",
        "0.0.6",
        "0.0.7",
        "0.1.0",
        "0.2.0",
        "0.2.1",
        "0.2.2",
        "0.2.3",
        "0.2.4",
        "0.2.5",
        "0.3.0",
        "0.3.1",
        "0.3.2",
        "0.3.3",
        "0.4.0",
        "0.4.1",
        "1.0.0",
        "1.0.1",
        "1.0.2",
        "1.0.3",
        "1.0.4",
        "1.0.5"
      ]
    }
  },
  "_attachments": {}
}
```

**Comment by mic159** [comment]
Looks like the old versions of require-from-string are back now!

**Comment by mic159** [comment]
Got a response from NPM:

> Thanks for reaching out. I apologize for the frustration.
> 
> We turned on a more nearby backing store that we had prepared before Saturday's incident for the Australia region but it had picked up some of the bad changes. We have reverted those changes and Australia is now using the previous backing store while we correct the new store.
> 
> The following versions should all be available once again.
> 
> :> npm view require-from-string versions
> 
> [ '1.0.0',
>   '1.0.1',
>   '1.0.2',
>   '1.1.0',
>   '1.2.0',
>   '1.2.1',
>   '2.0.0',
>   '2.0.1' ]
> Please let us know if there is anything else we can do for you. We’ll be here to help.
> Ernie

**Comment by silkentrance** [comment]
@jyotirmaybanerjee you are required to close once this was fixed.

**Comment by soldair** [comment]
fixed afaik
