### ISSUE TITLE
No valid versions available for package

### ISSUE THREAD

**Issue by nequibc** [npm/registry-issue-archive#276]
Hi,

I'm still having the same issue about "No valid versions available for package"
This is the last part of the trace where error appears:
[2018-02-01T20_16_44_272Z-debug.log](https://github.com/npm/registry/files/1687074/2018-02-01T20_16_44_272Z-debug.log)

988 silly resolveWithNewModule minimist@0.0.8 checking installable status
989 silly fetchPackageMetaData error for package@>= 1.0.0 < 1.2.0 No valid versions available for package
990 verbose type range
991 verbose stack package: No valid versions available for package
991 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:19:11)
991 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
991 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
991 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
991 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
991 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
991 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
991 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
991 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
991 verbose stack     at runCallback (timers.js:785:20)
991 verbose stack     at tryOnImmediate (timers.js:747:5)
991 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
992 verbose cwd C:\test
993 verbose Windows_NT 6.1.7601
994 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
995 verbose node v8.7.0
996 verbose npm  v5.4.2
997 error code ENOVERSIONS
998 error No valid versions available for package
999 verbose exit [ 1, true ]

**Comment by maharrg** [comment]
Hi; we’re aware that this package is temporarily inaccessible, and work is underway. Updates on the issue can be found here: https://status.npmjs.org/. You can also follow @npmstatus for updates.

**Comment by Spongman** [comment]
`package` has 10K downloads per day. my travis-ci builds just started failing. i was going to email their support 'cos i though there's no way package dependencies could just disappearfrom npm like they never existed...

**Comment by nequibc** [comment]
aaaa ok thank you, Also this package seems to have the same problem grunt-aws-lambda

**Comment by ashleygwilliams** [comment]
hi @nequibc! the status incident has been resolved and all packages have been restored. i will be closing this issue but please feel free to reopen if you continue to have trouble. thanks for your patience and understanding!
