### ISSUE TITLE
Gzip for specific package not available

### ISSUE THREAD

**Issue by alexanderstudte** [npm/registry-issue-archive#286]
I use a Verdaccio server as npm cache which downloads gzip files for the packages.

For one specific package this fails from time to time by returning either a 404 or 500 status code: babylon

Currently, when I try to open this URL manually I get the following result:

```
$ curl -i https://registry.npmjs.org/babylon/-/babylon-%5E7.0.0-beta.40.tgz
HTTP/2 500
date: Thu, 08 Mar 2018 14:47:30 GMT
content-type: application/json
cache-control: max-age=0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-fra19141-FRA
x-cache: MISS
x-cache-hits: 0
x-timer: S1520520449.429430,VS0,VE1225
content-length: 69

{"code":"InternalError","message":"tmpUrl.indexOf is not a function"}
```

This looks like a bug in the registry.

**Comment by soldair** [comment]
it looks like you have a typo in the dist url for that tarball
the url in the packument is https://registry.npmjs.org/babylon/-/babylon-7.0.0-beta.40.tgz

there is a bug that makes that bad error message though ill track it so it gets fixed. please reopen if ive misunderstood.
