### ISSUE TITLE
@types/webpack is broken

### ISSUE THREAD

**Issue by Alexander-Taran** [npm/registry-issue-archive#292]
npm -i @types/webpack results in  `404 http not found`

related issue on definitely typed:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24347

sorry if this is the wrong place to report 
could not find any better

**Comment by soldair** [comment]
This is a great place to report thanks!

**Comment by geomorillo** [comment]
I think this is a high priority bug and  should be fixed asap please many things are broken

**Comment by soldair** [comment]
absolutely agree. working on it

**Comment by aouji** [comment]
As a workaround for dev, I manually downloaded the tar file from `https://registry.npmjs.org/@types/webpack/webpack-3.8.8.tgz` (removing the `-/` from the url) and then copied the contents to `node_modules/@types/webpack`

**Comment by soldair** [comment]
very weird that url shouldn't work at all. thanks for the info!

**Comment by soldair** [comment]
all fixed thank you for your patience!

**Comment by geomorillo** [comment]
seems like its fixed thanks

**Comment by Alexander-Taran** [comment]
@soldair would you please share what was it? If possible.
