### ISSUE TITLE
packages kitsu and kitsu-core have unaccessible directories in their packed.tgz

### ISSUE THREAD

**Issue by etamponi** [npm/registry-issue-archive#293]
When I download the `packed.tgz` file from the registry for kitsu and kitsu-core, and then I uncompress it, I find a directory that I can't cd into. The reason is that the directory permissions are set to 644 instead of 755. Can this be solved?

It happens at least with v5.0.5, v5.0.6, v5.0.0, v4.6.0, and probably with all other versions.

Thanks in advance!

**Comment by soldair** [comment]
tarballs are immutable sadly. the author may have to publish new patch versions.
also if we change the tarball the shasum wont match and the cli wont install it.

**Comment by etamponi** [comment]
So it is possible that the package has been uploaded with the wrong directory permissions?

**Comment by wopian** [comment]
`kitsu` and `kitsu-core`'s published directories/files have `775` and `644` permissions respectively at the time of upload. I don't know why the directories are mutated into `644` in the registry.

**Comment by soldair** [comment]
The files are hashed on the computer that runs npm publish and can't be changed in the registry. It's likely a bug with how the tarball was made. The publisher might consider emailing support@npmjs.com for help. :)

**Comment by wopian** [comment]
One of my devices had its `umask` unknowingly changed, which was mutating directories in the tarball creation. Having resolved this `npm pack` and publishing via `yarn` produce the correct tarball on that device, so this can be closed now.

Ref: https://github.com/wopian/kitsu/issues/152#issuecomment-374253969

**Comment by etamponi** [comment]
Thank you!
