### ISSUE TITLE
Publish hooks no longer firing on private user scope 

### ISSUE THREAD

**Issue by Nicktho** [npm/registry-issue-archive#294]
Hello, I have set up a few hooks for a private user with the "scope" type. It appears that publish events stopped being triggered at exactly 3:00pm 16th March. Multiple publishes have been made since with no event fired.

Results from `wombat ls`:

```
 REDACTED │ scope      │ @REDACTED    │ https://REDACTED.com.au 
  triggered Mar 16, 2018 3:00 PM │ 200 
```

I've redacted sensitive information that i'm happy to share with in a private channel. Last publish was within the hour.

**Comment by soldair** [comment]
this should be fixed now. thanks for the heads up and sorry for the error.

**Comment by Nicktho** [comment]
Thanks a lot for the fix and speedy response! Amazing!

Is there anything you can share on what caused the error? :)

**Comment by Nicktho** [comment]
@soldair Has the api for hooks changed recently? I'm struggling to find information, but it appears now on a publish i'm receiving a `package:change` event instead of a `package:publish`, `package:change` does not have the new version in `change.version` where as `package:publish` does. 

I can't find any documentation about these responses so i'm not sure if this is the best place to post this.

**Comment by soldair** [comment]
@Nicktho it shouldn't have changed =) 
it may be that the object looks different now :thinking: 
when we have no previous version of the package to compare in the hooks system. as in the first hook ever for a package the event triggered is always "change".

ill take a look and see whats going on.

**Comment by Nicktho** [comment]
ah that makes sense, perhaps just the first hook is change and the following are publish

**Comment by soldair** [comment]
yeah if a bunch of changes piled up it might not look like just a publish anymore.

**Comment by kbluescode** [comment]
@soldair @Nicktho has this been officially resolved?

**Comment by Nicktho** [comment]
@kbluescode Seemed to be a one-off issue. I no longer work at company that manages this NPM account although at the time hooks resumed as normal.
