### ISSUE TITLE
Some modules are experiencing 404's since that last tarball server incident 

### ISSUE THREAD

**Issue by JADurham909** [npm/registry-issue-archive#3]
This one in particular is still not found.

`npm ERR! fetch failed https://registry.npmjs.org/mocha-junit-reporter/-/mocha-junit-reporter-1.11.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404`

**Comment by soldair** [comment]
i believe this module was effected by the issue in the latest update.
http://status.npmjs.org/incidents/7n06gj3f83tz

I'm looking into these now.

**Comment by soldair** [comment]
here are a list of publishes that were effected just. we are working to clean up the failed versions.

https://gist.github.com/soldair/b186df0622d6fa96620add9f3dbf95dd
