### ISSUE TITLE
readme is randomly empty on payload response

### ISSUE THREAD

**Issue by juanpicado** [npm/registry-issue-archive#305]
I just noticed that registry is returning a payload with readme (root) property empty randomly in some packages, for instance:

* https://registry.npmjs.org/react (it has readme)
* https://registry.npmjs.org/jquery (it has readme)
* https://registry.npmjs.org/pacote (it has readme)
* https://registry.npmjs.org/npm (it is empty)
* https://registry.npmjs.org/core-js (it is empty)

Also, taking react as an example, since version `16.3.0-alpha.1` a `readme` and `readmeFilename` property is being appended to each version, before that, none version has such properties. I've been analyzing other packages where I've seen the same, I could not find any pattern for it.

I'm just trying to understand what has changed recently because afaik this was working a couple of weeks ago. Am I wrong?

https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#package-metadata

btw, I'm trying to investigate the root of this issue https://github.com/verdaccio/verdaccio/issues/640 and then is when I noticed what I'm reporting.

**Comment by aremishevsky** [comment]
Hi @juanpicado 
Changes from https://github.com/verdaccio/verdaccio/pull/687 fixed this issue as well.
You can close this ticket too.

**Comment by juanpicado** [comment]
Also, it seems fixed.
