### ISSUE TITLE
Feature: Add support for registry package to be linked to github instead of duplicating

### ISSUE THREAD

**Issue by prasannavl** [npm/registry-issue-archive#31]
Currently, the procedure most commonly is this, for public packages.
1. Develop on GitHub.
2. Commit.
3. Tag releases.
4. publish to npm registry.

However, npm also supports directly from Github. However, publishing to npmjs has the advantage of discovery through the registry. Since a major percent of it is on GitHub anyway, why not allow package to be aliased?

**The Proposal (TL;DR)**
- npm registry will show the package and everything will behave exactly the same way. 
- I can search npm, find `history-next` - install. 
- Under the covers, it simply does `npm install prasannavl/history-next` (which uses GitHub). 

**What gets better:** 
- No more double publishing (One to GitHub, one to npm). npm tracks GitHub.
- Any GitHub repo can be discovered through npm with just possibly just a simple single `publish` command with an alias.
- No more out of sync READMEs between GitHub, and npms.
- The publishing step becomes a one-time process. Publish once and forget. GitHub tags are release versions. (These mechanisms are already in place).

**Explanation:**

Now, I have a package `prasannavl/history-next`. Its on GitHub. And its published on npm. I can install from npm with `npm install history-next`. I can also install with `prasannavl/history-next` to do the same from GitHub. GitHub tags also serve the versioning process nicely. 

My point is, **the maintenance of both GitHub, and then replicating it to npmjs, is highly repetitive, and painful when not using a build system to automate it**. Again, adding more complexity. I _really want to unpublish my package now, and simply just use `npm install prasannavl/history-next`_. But the reason I don't is because it would serve the **discovery** through npm. 

Now, if npm just allowed alias to GitHub, all these goals are accomplished without replicating, making the whole process simpler. And as an added advantage, if many projects are simply directly aliased, relives a huge load off npm servers. 

The only downside is possibly the single point of failure - GitHub. (Which honestly, I don't think is a huge problem for a huge number of projects on npm). And even so, practically, with all due respects, GitHub servers have historically been a lot more reliable than npm. And let's face it - if GitHub is down, the OSS world comes to down to a halting stop (well, not really, but I think the exaggeration is justified in credit to GitHub :)) And when that's a concern, there's also nothing stopping the authors for doing the exact same model that exists today - Everybody wins (rarely does this statement ever fit so aptly)

**Comment by ashleygwilliams** [comment]
hey! thanks for sharing this. i can def relate to the feeling that pushing to both the registry and Github is redundant.

that'd being said, i don't think this will ever be implemented. there are several reasons:
- the `.npmignore` and `.gitignore` files can be different. i.e. people push different things to the registry than version control. classically, people will push built files to the registry, but not version control. dealing with the edge cases/fallbacks if we allowed this aliasing would get complicated fast.
- we care about the near-immutability of the registry. allowing unpublishes would potentially lead to another `left-pad`, and the team is def not up for that.
- we don't want to go down when GitHub does. that's important to us.

we allow people to use git URLs as packages and i think that's about as far as our support will go right now. there are a number of downsides and a whole bunch of implementation and maintenance if we did this, for eliminating a single CLI command, which doesn't fit our goals at this time. also: we offer dist-tags if that is a feature you are interested in: https://docs.npmjs.com/getting-started/using-tags

fwiw, there are ways you can automate your npm publish through CI, e.g. https://docs.travis-ci.com/user/deployment/npm. that's probably a better way to solve this problem! lemme know if you have any followup questions, and thanks for contributing!

**Comment by nexdrew** [comment]
@prasannavl To help ease the burden of cutting and publishing new releases, you might want to look into these tools:
- [semantic-release](https://www.npmjs.com/package/semantic-release): Fully automated publishing on merge to master (based on commit message conventions)
- [standard-version](https://www.npmjs.com/package/standard-version): Automatic semver bumping, changelog generation, and git tagging (based on commit message conventions) - just without the auto push/publish
- [np](https://www.npmjs.com/package/np): One step CLI tool to run sanity checks, bump version (version type must be manually specified), and publish/push a new release

**Comment by prasannavl** [comment]
Hi. @ashleygwilliams, @nexdrew, thanks for the detailed reply. Yes, I'm aware of the tools to simply the things. But I was hoping linking to GitHub repos would be simplify the process even without some of the tooling. 

Though the other problems could potentially be solved given the intention and investment in time, I do understand the problems with unpublishing. That makes sense. Could be more complicated at best when taken out of the npm ecosystem. 

Cheers.
