### ISSUE TITLE
Consuming dependency data from the registry

### ISSUE THREAD

**Issue by zeke** [npm/registry-issue-archive#32]
Hi @soldair and @ashleygwilliams!

I want to make a thing that watches the registry for changes, looking for specific `dependencies` and `devDependencies` in the packages.

@bcoe directed me to https://github.com/jcrugzz/changes-stream, which I have working with https://skimdb.npmjs.com/registry

repo: https://github.com/zeke/ch-ch-ch-changes

``` js
const ChangesStream = require('changes-stream')

var changes = new ChangesStream({
  db: 'https://fullfatdb.npmjs.com/registry',
  include_docs: true
})

changes
  .on('readable', function () {
    var change = changes.read()
    console.log('\n\n\n')
    console.dir(change)
  })
  .on('error', function (err) {
    console.error(err)
  })
```

However I don't see any dependencies in those objects. Here's some sample output: https://gist.github.com/zeke/052cb82efbd578a8fd9abf66b60311a3

I tried changing the URL to https://fullfatdb.npmjs.com/registry thinking that might yield more metadata, but that host doesn't seem to work:

```
{ Error: getaddrinfo ENOTFOUND fullfatdb.npmjs.com fullfatdb.npmjs.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'fullfatdb.npmjs.com',
  host: 'fullfatdb.npmjs.com',
  port: 443 }
```

**Comment by soldair** [comment]
They are in the versions property of change.doc.

Try `console.log (JSON.stringify (change.doc,null,'  '))`

So the nested objects dont get flattened 

Also you can clean the document so it matches what you get from curling the document directly with normalize-registry-metadata

**Comment by zeke** [comment]
Yesss. Thanks!

**Comment by ashleygwilliams** [comment]
hey @zeke here's the follower i'm working on... sometimes examples help! https://github.com/npm/readme-tester/blob/master/index.js#L9

**Comment by zeke** [comment]
Thanks, @ashleygwilliams.

``` js
// stop after we've parsed all the things
if (change.seq >= end_sequence) {
  console.log(Summarize(parseTimes));
  process.exit(0);
}
```

Wondering about the need for this code. Is there not an `end` event for the stream? Does it just remain open and continue reading as new publish events occur?

**Comment by ashleygwilliams** [comment]
hey @zeke - 

yes, my (perhaps incomplete) understanding is that this feed does not exit as it is all the changes, so if you want o exit on "have completed all the changes since process started" this is the way to go :)

p.s. i've started a tutorial, would love you input https://github.com/npm/registry/pull/33

**Comment by ashleygwilliams** [comment]
oh also! @zeke if you wanna pair on a thing i am SO DOWN. literally hmu anytime :)

**Comment by zeke** [comment]
Thanks for your help, you two. Here's the result of tonight's dip into the registry: https://github.com/zeke/electron-npm-packages#readme
