### ISSUE TITLE
NPM registry is down, but status monitor says it is up

### ISSUE THREAD

**Issue by csvan** [npm/registry-issue-archive#324]
*UPDATE 3: Aaaaand it's down again.*

*UPDATE 2: Seems to be back to normal now.*

*UPDATE: Writing this, the status monitor shows "degraded performance". This is not accurate either - the registry is entirely unreachable.*

As of writing this, the NPM registry is down due to HAProxy issues, responding either with an explicit error message to this effect, or else a 504. This has been the case for at least an hour at this point.

However, the NPM status monitor says all systems are operational:

https://status.npmjs.org/

What exactly is the status monitor pinging? It clearly does not reflect the actual state of the registry.

**Comment by DanielRuf** [comment]
> UPDATE 2: Seems to be back to normal now.

Unfortunately not fully recovered, still not seeing any new published versions.

https://status.npmjs.org/
https://github.com/npm/npm/issues/20711

**Comment by ph3n0m666** [comment]
Agreed, over 2 hours now for myself, and still the same

**Comment by rarkins** [comment]
It's a pity when companies don't take their status pages seriously. I wish outage postmortems assessed whether the status page was accurate and resolved internally to fix it before the next time.

**Comment by maharrg** [comment]
Thanks for reaching out and reporting this. Our team is currently investigating this issue and we hope to have more information shortly. If you'd like, you can follow this status update with more information here:

https://status.npmjs.org/incidents/3rjzvts6v98k

**Comment by ph3n0m666** [comment]
ok as an update, its working for me now - it slowly filtered and updated, I can now confirm the latest version for my dev package is correct :)

so huzzah!

**Comment by schalkneethling** [comment]
Working for me as well. Latest version is being installed. Thanks!

**Comment by Reinmar** [comment]
It worked for a moment (packages published ~5h ago appeared on the website and can be download) but it's down again now (packages published 30 minutes ago are not available).

**Comment by DanielRuf** [comment]
Seems to work fine now.

**Comment by xemasiv** [comment]
> What exactly is the status monitor pinging? It clearly does not reflect the actual state of the registry.

This intrigues me, maybe its the HAProxy responding to pings (since it's still up, sending 5xx errors) and not the actual service it's proxying.. but who knows lol.

**Comment by feonit** [comment]
i have same problem, but i publish it to here https://github.com/npm/www/issues/417

**Comment by csvan** [comment]
Seems to be down again

**Comment by transitive-bullshit** [comment]
@csvan this issue is reproducible again for a bunch of us over at https://github.com/yarnpkg/yarn/issues/4771

**Comment by mharr171** [comment]
Down again

**Comment by transitive-bullshit** [comment]
For anyone else ending up here, this [issue](https://github.com/yarnpkg/yarn/issues/5885#issuecomment-392215450) appears to be where the action is taking place in real-time.
