### ISSUE TITLE
registry does not list new published version

### ISSUE THREAD

**Issue by yamass** [npm/registry-issue-archive#327]
I have published my package “trivial-components”.

**What worked as expected:**
* When I did "npm publish” I got the usual publishing confirmation email: "Successfully published trivial-components@0.3.2"

**What does not work:**
* When I try to install the newly released version, I get the following error: 
**npm**: `npm ERR! code ETARGET
npm ERR! notarget No matching version found for trivial-components@0.3.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
`
**yarn**: Couldn't find package "0.3.2" on the "npm" registry.
* The registry does not list the new version: https://registry.npmjs.org/trivial-components
* Also, the new version does not appear on the npm registry’s website: https://www.npmjs.com/package/trivial-components (still displays version 3.0.0) (UPDATE: the website is now correct, but the other (main) issues remain)

**Comment by pauljmelia** [comment]
I can confirm the same is happening with one of my packages: 'devextreme-data-breezejs'.

The latest version I've published is 16.2.7, and I have received the confirmation email to that effect.

Registry is listing the latest version as 16.2.5.

**Comment by pauljmelia** [comment]
#324

**Comment by oleics** [comment]
#318

**Comment by amb26** [comment]
I have the same issue with respect to "gpii-pouchdb". Issued two releases this morning, neither have appeared

**Comment by dvejmz** [comment]
Happening also with `cardinal`. Version 2.1.0 was published yesterday and is listed as available on the module's npmjs page but I'm still getting "package version not found" errors whenever I try to install it. Hitting [the registry](https://registry.npmjs.org/cardinal) returns an older version of the module (2.0.1).

**Comment by tyroroto** [comment]
Same issue here 
npm 5.5.1

**Comment by arjun-kava** [comment]
same issue with 5.6.0

**Comment by pwambach** [comment]
Same problems here with a private package and npm 6.0.1

**Comment by DanielRuf** [comment]
Still the same =( https://github.com/npm/npm/issues/20711

**Comment by rarkins** [comment]
This has lasted for some time. renovate@v12.30.11 is missing from the registry response and it was published 13 hours ago. I published ("successfully") v12.30.12 over the top now but the registry still returns older versions.

**Comment by SylvainEstevez** [comment]
Same issue here with https://www.npmjs.com/package/@bluejay/sequelize-service.

NPM version: 5.8.0

**Comment by molinto** [comment]
Same here :(

**Comment by prachiagrawal94** [comment]
+1

**Comment by shaybagants** [comment]
Another example:
https://www.npmjs.com/package/punycode shows 2.1.1 version as latest (updated 11 hours ago) while 2.1.1 version is missing from the metadata url (https://registry.npmjs.com/punycode).

**Comment by aharris** [comment]
I am having the same issue with sass-flex-grid.

If you look at my packages it has the correct version number:

https://www.npmjs.com/settings/busypixels/packages

![image](https://user-images.githubusercontent.com/713398/40371934-9fb04256-5db1-11e8-8c65-446853d9c4ae.png)

However if you look at the details page it is old:

https://www.npmjs.com/package/sass-flex-grid

![image](https://user-images.githubusercontent.com/713398/40371961-b2669350-5db1-11e8-938c-96fac88d570f.png)


From CLI:
```
$ npm publish
npm notice
npm notice 📦  sass-flex-grid@1.0.2
npm notice === Tarball Contents ===
npm notice 1.2kB  package.json
npm notice 1.9kB  _classes.scss
npm notice 740B   _defaults.scss
npm notice 250B   _helpers.scss
npm notice 1.2kB  _mixins.scss
npm notice 182B   .editoconfig
npm notice 148B   index.scss
npm notice 2.1kB  README.md
npm notice 22.2kB docs/dist/grid.css
npm notice 1.6kB  docs/dist/index.css
npm notice 31.1kB docs/images/GitHub_Logo_White.png
npm notice 17.3kB docs/index.html
npm notice 2.0kB  docs/index.scss
npm notice 2.3kB  docs/lib/prism.css
npm notice 9.9kB  docs/lib/prism.js
npm notice === Tarball Details ===
npm notice name:          sass-flex-grid
npm notice version:       1.0.2
npm notice package size:  43.0 kB
npm notice unpacked size: 94.1 kB
npm notice shasum:        00d798e68c3f5720b0a5abf6bf669a373960056f
npm notice integrity:     sha512-//xoMUHhXpKFh[...]XoN+00a4KCeCQ==
npm notice total files:   15
npm notice
+ sass-flex-grid@1.0.2
```

```
$ npm view --registry https://registry.npmjs.org/ sass-flex-grid

sass-flex-grid@0.0.0 | ISC | deps: none | versions: 1
Flexbox grid for sass (scss). Inspired by http://flexboxgrid.com/
https://github.com/aharris/flex-grid-sass#readme

dist
.tarball https://registry.npmjs.org/sass-flex-grid/-/sass-flex-grid-0.0.0.tgz
.shasum: 50eaeae8322131ab904de93c0e20c6ec8e91aeec
.integrity: sha512-nlhhejG/63xL7AUVjdo8Az42LfiEmLgg0brZCqJCC8LLi7ZThameyTW8/wLnAZVMtCYnjokockO1tpSDu8PsYQ==
.unpackedSize: 627 B

maintainers:
- busypixels <ashtonharris.me@gmail.com>

dist-tags:
latest: 0.0.0
```

**Comment by schalkneethling** [comment]
The page listing the package now correctly reflects the latest version but, npm i still installs the old version.

**Comment by dvejmz** [comment]
A new version of cardinal has been published and it finally appears correctly on the npm registry. I guess this deployment was done with npm registry on a better state and was successful this time around.

**Comment by yamass** [comment]
My new trivial-components version is also deployed now. (the one from 9 hours ago)

**Comment by s-h-a-d-o-w** [comment]
It simply popped up after those 9 hours without you doing anything?
If that's the case, I suppose people shouldn't bet on things getting resolved this "quickly" - my package has been on the npmjs website for "a day" but still nothing on the registry.

**Comment by dvejmz** [comment]
Unfortunately that was the case @s-h-a-d-o-w . I took no action whatsoever to solve this issue on my end. I guess I was lucky enough the maintainers of the package I depend on (cardinal) decided to publish a new version today after these alleged fixes to the registry were put in place.

This makes me guess any new publications from now on should appear within minutes on the npm registry. Don't know if npm will take any further action to sort this out for everyone but hopefully they'll do.

**Comment by jamesplease** [comment]
Just poppin' in here to say that I released a new version of `materialish`, v0.1.2, early this AM (around 7:30am PST), and it still not available to be installed, so it seems like this is still ongoing, even though there haven't been any updates on the status page for a few hours.

**Comment by oleics** [comment]
Situation now is:
https://registry.npmjs.org/ac-json-apis
shows 0.0.6
npm still installs 0.0.5
even after cleaning every local cache

**Comment by rarkins** [comment]
I hit a problem today where another of my packages was still missing its most recently published version. That missing version only appeared once I made an "empty" patch update and published it.

**Comment by oleics** [comment]
And another one:

https://www.npmjs.com/package/ac-vue-app
=> 0.0.5

https://registry.npmjs.org/ac-vue-app
=> 0.0.4

npm install ac-vue-app
=> 0.0.4

**Comment by rarkins** [comment]
Unfortunately the npm team seem unaware of this “lost versions” error and only focused on restoring new publishing success. They have closed the open status event and marked all systems as green. Seems like if you publish a new version now then the missing one before it will reappear, but only then. I suggest you email their support if you want them to acknowledge this issue.

**Comment by oleics** [comment]
ping @soldair

**Comment by rarkins** [comment]
@oleics I notice that the versions you mentioned now seem correct on the registry. Did you do anything to repair them or does it look like it got updated independently on the backend? If the latter then it looks like it's truly resolved now, which is great news.

**Comment by oleics** [comment]
@rarkins it did update like magic ca one hour ago.

**Comment by jamesplease** [comment]
Just a heads up, **this may be happening again**!

30 minutes ago, I published `materialish@0.2.0`. It was available for download immediately.

10 minutes ago, I published `materialish@0.2.1`. It is still not available for download. npm may just be going slow, but it is usually instant, which suggests this may be a regression.

I'll update this issue once 0.2.1 becomes available.

**Comment by jefflembeck** [comment]
Hi all. Let me know if you're still having problems with a package (if so, please list the package). We're watching this closely and there are definitely still some spots.

**Comment by sentience** [comment]
I’m seeing this issue with a couple of newly-published versions of our package. Versions 0.2.4 and 0.2.5 of cultureamp-front-end-scripts are not showing up in the registry or the website, although I have received publish confirmation emails for both.

```
❯ npm publish
+ cultureamp-front-end-scripts@0.2.5

❯ npm view cultureamp-front-end-scripts

{ name: 'cultureamp-front-end-scripts',
  'dist-tags': { latest: '0.2.3' },
  versions: [ '0.0.1', '0.0.2', '0.1.0', '0.2.0', '0.2.1', '0.2.2', '0.2.3' ],
```

**Comment by sentience** [comment]
Ping @jefflembeck

**Comment by boygirl** [comment]
Just published `victory-core@21.1.3`. I received a confirmation email, and `victory-core@21.1.3` shows up as the most recent version on the registry website, but when I try to install it in a different project, I get: `npm ERR! notarget No matching version found for victory-core@^22.1.3`.

Possibly unrelated, but I also notice that the last publish time listed on the registry website is stale. It seems stuck at 41 minutes: https://www.npmjs.com/package/victory-core

**Comment by sentience** [comment]
Looks like `cultureamp-front-end-scripts` is now showing the correct version on the web, but `npm view` is still outputting obsolete data.

**Comment by jt-nti** [comment]
Published several modules today (below), which seem to be showing up with the latest version, and tagged correctly, using `npm view`. Unfortunately I get an error when trying to install any of them at the new version:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for composer-wallet-inmemory@0.19.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'composer-admin'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-05-24T12_29_55_438Z-debug.log
```

The modules which should have been published at 0.19.6:

composer-admin composer-rest-server composer-cli composer-ru
ntime composer-client composer-runtime-embedded composer-common composer-runtime
-hlfv1 composer-connector-embedded composer-runtime-pouchdb composer-connector-h
lfv1 composer-runtime-web composer-connector-proxy composer-connector-server com
poser-connector-web composer-wallet-filesystem composer-cucumber-steps composer-
wallet-inmemory composer-documentation composer-playground generator-hyperledger
-composer composer-playground-api loopback-connector-composer composer-report

Update: it looks like they did eventually get to the point where they can be installed so, like @jamesplease, it seems like there's currently an unusually high latency between publishing modules and being able to install them

**Comment by boygirl** [comment]
`victory-core@21.1.3` is installing as expected as of this morning. :)

**Comment by jamesplease** [comment]
@jefflembeck , I'm seeing atypically high latency between publishing new versions of `materialish` and when they are able to be installed or read from the registry. It can range from 15minutes to over 1 hr (I went to bed after about 1 hr, so I am not sure when one version ultimately became ready to be installed).

This is atypical from my experience, because for the past few years npm has been admirably speedy; effectively instant.

Thanks for your continued investigation!

**Comment by sentience** [comment]
The missing `cultureamp-front-end-scripts` versions became fully available overnight.

**Comment by StarpTech** [comment]
Same issue here with [nats-hemera](https://www.npmjs.com/package/nats-hemera?activeTab=versions). I can publish it again and again with no error. The version isnt't listed and can't be installed.

```
E:\Repositorys\hemera\packages\hemera [master ≡]> npm publish
+ nats-hemera@5.6.0
E:\Repositorys\hemera\packages\hemera [master ≡]> npm publish
+ nats-hemera@5.6.0
E:\Repositorys\hemera\packages\hemera [master ≡]> npm publish
+ nats-hemera@5.6.0
E:\Repositorys\hemera\packages\hemera [master ≡]>
```

https://github.com/lerna/lerna/issues/1438

**Comment by 1stvamp** [comment]
Okay folks, just wanted to let everyone know we're aware of what's causing this and I have a batch job running to fix it. I expect `async-validator==1.8.2` specifically to be available again in ~1 hour, will update this issue with more detail later.

**Comment by Yanjiie** [comment]
Same issue here with weex-flymeui.

**Comment by json-sun** [comment]
Same issue here with [weex-flymeui](https://www.npmjs.com/package/weex-flymeui).
I publish a new version but not found in [the package pages](https://www.npmjs.com/package/weex-flymeui).
```
+ weex-flymeui@0.1.18
```

**Comment by mjancarik** [comment]
@jefflembeck I have same problem.

missing versions:
infinite-circle@0.0.5, infinite-circle@0.1.0
to-mock@1.2.2

**Comment by StarpTech** [comment]
Check the solution in my issue [here](https://github.com/npm/registry/issues/333).

> And there we have it: This is a failure mode when your registry is entered with an http:// protocol, instead of https://.
Check your config, .npmrc file, etc.

Change protocol to `https://` in .npmrc solved my issue.

**Comment by billyjanitsch** [comment]
@jefflembeck I'm seeing this issue with babel-preset-kensho (4.0.0-alpha.11)

**Comment by yamass** [comment]
I'm closing this issue since there is no more activity and I have not experienced any problems with publishing for some weeks now.
