### ISSUE TITLE
Registry returns 404 for a package I have installed before

### ISSUE THREAD

**Issue by ryaninvents** [npm/registry-issue-archive#329]
I'm setting up a brand-new Ubuntu laptop to work with my projects, and I'm getting a 404 from the registry on a package I know I've successfully installed before. The 404 is being returned for `natives@1.1.4`.

To reproduce the issue, run:

```bash
mkdir test-case
cd test-case
npm init
# Accept all default values

npm install --save-dev gulp
```

My dependency on `natives` is via `gulp@3.9.1 > vinyl-fs@0.3.14 > graceful-fs@3.0.11 > natives@1.1.4`.

Error message:

```
npm ERR! code E404
npm ERR! 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.4.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ryan/.npm/_logs/2018-05-25T23_34_25_326Z-debug.log
```

See [`npm-debug.log`](https://gist.github.com/ryaninvents/3fd9b30dd484292ffeb0d00176e119ce) for details.

```
➜  ~ node -v
v8.11.2
➜  ~ npm -v
5.6.0
```

Note: to me, this seems different from #327 since I am not publishing the package myself. However, it appears as though [natives 1.1.4 came out 4 days ago](https://www.npmjs.com/package/natives), so it's possible the two issues have the same root cause.

**Comment by dylanlrrb** [comment]
I'm also seeing this issue in my Ci/Cd environment. `Error: fetch failed with status code 404` for several packages which is causing builds to fail
also tried fetching from the registry on my local machine and am getting the same error

eg. npm install angular@1.3.2
node --version
v6.9.5
npm --version
3.10.10

**Comment by dotcarls** [comment]
Also seeing 404s: `verbose stack Error: 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.4.tgz`

```
npm ERR! code E404
npm ERR! 404 Not Found: natives@latest
```

**Comment by tmadej** [comment]
I'm seeing 404s on natives@1.1.4 & babel@5.8.38 while building via Travis CI for projects that were previously building without errors and had no code changes.

I'm having the same issue locally and in cloud services in AWS.

$ node --version
v8.11.2
$ npm --version
5.6.0
$ nvm --version
0.33.11

**Comment by jstacoder** [comment]
same here, cant build!!! wtf npm

**Comment by metafour** [comment]
I tried specifying older versions in my `package.json` and am getting 404s on those as well. Tried 1.1.3, 1.1.2, 1.1.1, and 1.1.0

**Comment by philipjscott** [comment]
It seems that the registry is down:

https://status.npmjs.org/
https://status.yarnpkg.com/

**Comment by joshuaavalon** [comment]
The status page said the problem is solved but I still having problem to install packages.

For example, https://www.npmjs.com/package/async-validator/v/1.8.2

npm return `{"error":"Not found"}` but the package exist and I install it yesterday.

**Comment by NeutralAngel** [comment]
Same issue here...

npm ERR! code E404
npm ERR! 404 Not Found: angular@1.6.10

**Comment by joerg84** [comment]
Same...

**Comment by Adam-Burke** [comment]
this https://www.npmjs.com/package/async-validator/v/1.8.2 is still failing

**Comment by indrajit-rathod** [comment]
npm ERR! code E404
npm ERR! 404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

The issue still exists

**Comment by xemasiv** [comment]
Every body which area are you from?

Heard on reddit there were AWS outages on US East, here in SEAsia everything runs smoothly.

Edit: Might be related https://github.com/yarnpkg/yarn/issues/5885

**Comment by MichaelBBTiger** [comment]
I have the same issue
error 404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

**Comment by NeutralAngel** [comment]
Interesting... I am from Indiana, so that would make sense.

**Comment by joshuaavalon** [comment]
@xemasiv SEAsia

I don't think that is the same issue because I am get a json response `{"error":"Not found"}` instead of cloudflare 403.

**Comment by LiangZugeng** [comment]
our VSTS builds failed due to 404 error for https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz, now we are unable to publish any more. The build agent locates at Azure data center in US East.

P.S. I also got 404 and {"error":"Not found"} by accessing the link directly in Safari and I'm in China, this could be a global issue.

**Comment by afc163** [comment]
+1

**Comment by mackiedrew** [comment]
@xemasiv Toronto

**Comment by Adam-Burke** [comment]
@xemasiv Sydney, Australia

**Comment by ryaninvents** [comment]
@xemasiv Tallahassee, FL

**Comment by joshuaavalon** [comment]
If someone need to get it working now, you can use Yarn registry `https://registry.yarnpkg.com/` and revert it back later `https://registry.npmjs.org/`.
```
npm set registry https://registry.yarnpkg.com/
```

It has all the packages I needed and it is a reputable source.

**Comment by LiangZugeng** [comment]
@joshuaavalon tried the yarn registry and still got the same error, seemed yarn just redirects requests to npm official registry.

4512 silly mapToRegistry uri https://registry.yarnpkg.com/async-validator
4513 verbose addRemoteTarball https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz not in flight; adding
4514 verbose addRemoteTarball [ 'https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz',
4514 verbose addRemoteTarball   'b77597226e96242f8d531c0d46ae295f62422ba4' ]
4515 info retry fetch attempt 1 at 1:49:18 PM
4516 info attempt registry request try #1 at 1:49:18 PM
4517 http fetch GET https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
...
4560 http fetch 404 https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4561 error fetch failed https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4562 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
4563 info retry fetch attempt 2 at 1:49:28 PM
4564 info attempt registry request try #1 at 1:49:28 PM
4565 http fetch GET https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4566 http fetch 404 https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4567 error fetch failed https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4568 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
4569 info retry fetch attempt 3 at 1:50:29 PM
4570 info attempt registry request try #1 at 1:50:29 PM
4571 http fetch GET https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4572 http fetch 404 https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
4573 error fetch failed https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

**Comment by wu-sheng** [comment]
Facing the same issue, at Apache SkyWalking,

**Comment by joshuaavalon** [comment]
@LiangZugeng It is not redirect. I am able to download from `https://registry.yarnpkg.com/async-validator/-/async-validator-1.8.2.tgz`. From the error log, you seems still downloading from ` https://registry.npmjs.org/`.

I removed my `node_modules`, set registry and replaced links in `package-lock.json` to ensure it downloads from `https://registry.yarnpkg.com/`.

**Comment by wu-sheng** [comment]
@joshuaavalon I already changed the source : https://github.com/apache/incubator-skywalking/pull/1269/files

But CI still fails.. https://travis-ci.org/apache/incubator-skywalking/builds/384100209?utm_source=github_status&utm_medium=notification

**Comment by juanpicado** [comment]
For those that the file **async-validator-1.8.2.tgz** is missing

```
 "https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz: Request failed \"404 Not Found\"".
```
you also might use  **taobao** (those are far away from USA) or **yarn** registry in the meantime. 
```
yarn install --registry https://registry.npm.taobao.org/ --no-lockfile
```

**Comment by wu-sheng** [comment]
It is complex process to change the register, considering Apache SkyWalking is not a nodejs project only. Hope this can be resolved soon.

I didn't want to start the changes.

**Comment by LiangZugeng** [comment]
@joshuaavalon I guess it's the package-lock.json issue, I will try to regenerate the file using yarn registry.

@juanpicado Taobao NPM registry was the first option I tried, with it the build agent spent 16 minutes to restore the packages (the machine locates @ central US in Azure data center) and still wan't able to finish the download with no output from npm install command (weird!).

P.S. Internet from US Azure to AliCloud Shenzhen data center in China seems also having some problems, our deployments all failed of pushing builds from US to AliCloud via SSH. Who said no deployments on Friday? Totally agree!

**Comment by joshuaavalon** [comment]
@LiangZugeng I just replaced them in notepad.

**Comment by 1stvamp** [comment]
Okay folks, just wanted to let everyone know we're aware of what's causing this and I have a batch job running to fix it. I expect async-validator==1.8.2 specifically to be available again in ~1 hour, will update this issue with more detail later.

**Comment by turnerniles** [comment]
@1stvamp Any update? https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz is still unavailable.

**Comment by vstepanyuk** [comment]
@1stvamp Any news?

**Comment by chrisdickinson** [comment]
Update: I've manually restored the missing tarball for async-validator@1.8.2, and installs should start working again.

**Comment by helmsb** [comment]
I can confirm it's working for me now. Thanks!

**Comment by turnerniles** [comment]
@chrisdickinson It works now. Thank you!

**Comment by hanahmily** [comment]
@chrisdickinson Great job! It has worked for me now. Thanks!

**Comment by ryaninvents** [comment]
Works for me now too!
