### ISSUE TITLE
Registry returns 500 'An error occurred' if Content-Length header is provided

### ISSUE THREAD

**Issue by oliverwoodings** [npm/registry-issue-archive#330]
According to the npm status page, some maintenance was started last night at 22:30 UTC. Shortly after this, our internal registry proxy started returning almost every single request with a 500 status code and the text `An error occurred`:

<img width="338" alt="screen shot 2018-05-26 at 06 48 56" src="https://user-images.githubusercontent.com/621323/40572977-fb07b95c-60b0-11e8-94a6-a8495b9f2df0.png">

Initially I blamed this on the outage that followed the maintenance work you guys were doing, however the problem persisted on our end even after the npm status page was updated to say everything is fine now.

After digging into it further, I have found what I believe to be the root cause. The issue happens when you provide the HTTP header `Content-Length` with a value of `0` when getting a package. cURL script that shows the issue:

```
curl https://registry.npmjs.org/error-ex -H "Content-Length: 0"
```

If you don't send that header, then it works fine.

My theory is whatever maintenance work that was performed last night has caused this new behaviour, since we have been sending this HTTP header for months now (our npm proxy has not changed at all in that time) with no issue. For reference, this it the proxy lib we are using that ends up adding the header: https://www.npmjs.com/package/express-http-proxy

Obviously on our end the quick solution is to stop sending that header, which we will do. However it would be good if the registry could not blow up on the presence of a lil' old header!

**Comment by oliverwoodings** [comment]
If anyone else happens to be using express-http-proxy for this purpose and needs a quick fix - you can set the `parseReqBody` option to false to stop it setting `content-length` to 0.

**Comment by mrodem** [comment]
We are seeing the same behavior when interacting with registry.npmjs.org through the `electron.net` module: https://electronjs.org/docs/api/net.

When using an intercepting proxy to examine the HTTP headers of the requests, I see a `Content-Length: 0` header. This seems to be added by `electron.net`, and I have not found a way to remove it. The problem is easily reproducible with this snippet:

```
const {app} = require('electron');

app.on('ready', () => {
    const {net} = require('electron');
    const request = net.request('https://registry.npmjs.org/underscore');
    request.on('response', (response) => {
        console.log(`STATUS: ${response.statusCode}`);
        console.log(`HEADERS: ${JSON.stringify(response.headers)}`);
        response.on('data', (chunk) => {
            console.log(`BODY: ${chunk}`);
        });
        response.on('end', () => {
            console.log('No more data in response.');
        });
    });
    request.end();
});
```

Output:

```
STATUS: 500
HEADERS: {
  "cf-ray": ["4220237968f842bb-OSL"],
  "content-length": ["17"],
  "content-type": ["text/plain;charset=UTF-8"],
  "date": ["Mon, 28 May 2018 10:46:39 GMT"],
  "expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],
  "server": ["cloudflare"],
  "set-cookie": ["__cfduid=da438cdb3d04191bcec7f476b0d1bb6c21527504398; expires=Tue, 28-May-19 10:46:38 GMT; path=/; domain=.npmjs.org; HttpOnly; Secure"],
  "status": ["500"]
}
BODY: An error occurred
No more data in response.
```

It would be nice if the registry could handle `Content-Length: 0`, as it seems that multiple libraries are sending this header by default.

**Comment by DanielRuf** [comment]
Could patch-package be a viable solution to patch the dependency until there is a better fix?

**Comment by oliverwoodings** [comment]
@DanielRuf not sure I follow - what are you suggesting? We've already found a workaround the problem for now.

**Comment by DanielRuf** [comment]
I meant @mrodem, patch-package can be used to change dependencies in a safe way and patch this header out of it.

**Comment by bencefr** [comment]
Issue got fixed: https://npm.community/t/issue-registry-returns-500-an-error-occurred-if-content-length-header-is-provided/1087

**Comment by oliverwoodings** [comment]
Awesome - thanks!
