### ISSUE TITLE
418 errors behind proxies are back

### ISSUE THREAD

**Issue by brandonpittman** [npm/registry-issue-archive#341]
Well, there's no mention of teapots, but the same 418 errors from two days ago are back.
 npm/npm#20836

**Comment by brandonpittman** [comment]
npm/npm#20836

**Comment by nick1740** [comment]
Yes the error from the 2 days are back, getting the error npm ERR! 418 I'm a teapot: <package>@latest

**Comment by pmahony893** [comment]
I routed `npm install angular` through cntlm (to get past my company's proxy), and then through fiddler (to capture the response body), and this was the response body:
`{"error":"got unknown host (registry.npmjs.org:80)"}`

**Comment by mcgrews3** [comment]
I think what is happening is the proxy or some other part in the chain is going with HTTP instead of HTTPS.  My theory is that the registry is returning HTTP 418 when it sees HTTP requests.

**Comment by AndyBan** [comment]
There are many corporate users out there who are stuck behind firewalls who are essentially forced to use http for their registry address as that is the only way that fiddler or other tools can inject ntlm headers for authentication.  

This issue is still occurring today.

**Comment by chris-dk** [comment]
Same problem here, we were using cntml to handle our corporate proxy. This was working without problems until today. Now we get this error. Tried to change the registry to https, but then it hangs with fetchMetaData. Tried px instead of cntml, but still the same problem. Would be thankful for any help :)

**Comment by thebalkanfella** [comment]
Had the same issue earlier today, behind corporate proxy. Seems to be working again as of 10 minutes ago

**Comment by ultraheroe** [comment]
I had the same issue. The solution was update the `registry` entry of my `npm config` (thanks to @predzme for the [solution](https://github.com/npm/registry/issues/335#issuecomment-393552098)) 
`npm config set registry  https://registry.npmjs.org/`
Note the _"s"_ at the end of the http part

**Comment by AndyBan** [comment]
I've noticed when running an npm upgrade it checks the registry for the latest versions which is successful over http but when it goes to download the files it calls the registry with port 80 on the end which is then rejected as it thinks its an unknown host.

npm shouldn't really putting port 80 on a http request but its technically correct so the fix here is really to have the registry accept http://registry.npmjs.org:80 as a valid host.
