### ISSUE TITLE
Download count is not working

### ISSUE THREAD

**Issue by Ffloriel** [npm/registry-issue-archive#342]
I noticed that the download count on npm is not working anymore.
Every packages seems to receive less download this week.

Every packages seems to be concerned.
[https://www.npmjs.com/package/react](https://www.npmjs.com/package/react)
[https://www.npmjs.com/package/babel-core](https://www.npmjs.com/package/babel-core)

**Comment by cronvel** [comment]
In fact, all stat-related stuffs seem to be broken recently... API for author's packages, package dependencies/depended upon, download count...

**Comment by IlyaKhD** [comment]
Checked about 10 packages, all the same: 0 daily downloads starting from May, 27 (28). 
E.g. the React [npm  downloads stats](https://npm-stat.com/charts.html?package=react&from=2018-05-25&to=2018-06-03).

**Comment by al-k21** [comment]
Seems like an issue with `last-week` period. E.g.:

- [`express#last-month`](https://api.npmjs.org/downloads/point/last-month/express): 15053756
- [`express#last-week`](https://api.npmjs.org/downloads/point/last-week/express): 0

**Comment by cronvel** [comment]
@al-k21 no, it's more like no more download counts are inserted. Your last-month stat will slowly deplete over the course of the month...

**Comment by detrohutt** [comment]
From https://status.npmjs.org/

>Investigating - We're investigating a known issue with download counts not being updated properly in the past few days.
>
>Jun 4, 17:30 UTC

You can subscribe to status updates for that issue from the same page.

**Comment by detrohutt** [comment]
It’s fixed: https://status.npmjs.org/incidents/b4ktc38pypd1

**Comment by detrohutt** [comment]
Well, it was supposedly fixed, but my package's download counts have still shown up as 0 on multiple days since then.

**Comment by Ffloriel** [comment]
Yes, the problem seem to have reappeared. On the home page, the _Downloads · Last Day_ is 0

**Comment by siddharthlatest** [comment]
Chiming in here, as I am seeing the same thing for the past week. Reference: https://npm-stat.com/charts.html?package=socket.io&from=2017-06-28&to=2018-06-28
