### ISSUE TITLE
I am getting an error code E418 

### ISSUE THREAD

**Issue by veeramanx** [npm/registry-issue-archive#343]
npm ERR! code E418
npm ERR! 418 I'm a teapot: @pnp/common@latest

**Comment by predzme** [comment]
Same issue here using _npm install_. I'm behind a company proxy. I tried with cntlm and still did not work.

**Comment by mcgrews3** [comment]
https://github.com/npm/registry/issues/341

**Comment by predzme** [comment]
solved the problem by editing the registry to https : _npm config set registry https://registry.npmjs.org/_

**Comment by veeramanx** [comment]
@Predzme thanks for the solution. it works

**Comment by eyvindx** [comment]
thanks, solved with
 npm config set registry https://registry.npmjs.org/
