### ISSUE TITLE
Cannot query replicate.npmjs.com

### ISSUE THREAD

**Issue by segrey** [npm/registry-issue-archive#358]
Querying
```
https://replicate.npmjs.com/registry/_design/app/_view/browseAll?group_level=2&skip=0&limit=7&start_key=%5B%22%40ang%22%5D&end_key=%5B%22%40angz%22%2C%7B%7D%5D
```
responses with
```
HTTP/1.1 404
npm-notice: this endpoint is deprecated
server: haproxy
```
Is it possible to restore handling such HTTP requests?

**Comment by dylanbutler** [comment]
We are seeing replicate.npmjs.com return 404s for us intermittently. Can someone please look into this?

**Comment by 1stvamp** [comment]
Hi there,

Sorry for the delay but issues on here can get missed easily (In future try https://npm.community/ as it can be a lot easier for us to pick up on new issues there).

Please take a look at the [announcement on the blog](https://blog.npmjs.org/post/173939360180/couchdb-browse-views-unavailable) re. these views being deprecated and how you can recreate them on your own couchdb instances if you really need them (we may in future provide API endpoints that also replicate the functionality of the views, time and resources permitting).
