### ISSUE TITLE
replicate.npmjs.com incomplete?

### ISSUE THREAD

**Issue by zeke** [npm/registry-issue-archive#37]
I'm trying out the new replication service, but for some reason I'm not getting all the packages.

Here's a repo to demonstrate the issue: https://github.com/zeke/replicate-npm-test/tree/master

When I use `https://skimdb.npmjs.com/registry`:

``` js
var registry = require('package-stream')()
```

I get this output:

```
count 297349
scoped? false
```

But when I change to the new db:

``` js
var registry = require('package-stream')({
  db: 'https://replicate.npmjs.com'
})
```

I see fewer packages:

```
count 282353
scoped? true
```

Any ideas?

cc @soldair

**Comment by ChALkeR** [comment]
@zeke Are you still observing this issue? `_byField` endpoint looks fine to me now — all data from `skimdb` seems to be present in `replicate`.

**Comment by zeke** [comment]
Haven't tried it lately, but I have observed replicate.npmjs.com to be more stable in the time since this issue was opened. Tentatively closing...
