### ISSUE TITLE
missing the new version: coffee@5.0.1

### ISSUE THREAD

**Issue by fengmk2** [npm/registry-issue-archive#379]
https://www.npmjs.com/package/coffee?activeTab=versions

![image](https://user-images.githubusercontent.com/156269/43752629-84d0b960-9a34-11e8-8dc6-31922e3530cb.png)

coffee@5.0.1 have been publish in `"5.0.1": "2018-08-07T03:07:33.027Z"`, but still can't access it on npm registry.

**Comment by fengmk2** [comment]
I receive the publish success email too.

![image](https://user-images.githubusercontent.com/156269/43752622-75971f48-9a34-11e8-83d2-b48c5bc414ca.png)

**Comment by 7etrahedral** [comment]
Confirmed occurs in my package too.
Publish is successful, but new version is not listed.

**Comment by ctrldavid** [comment]
Same issue here. Tried a couple of times now and the publish command says it worked but `npm show . version` doesn't list the new version.

**Comment by azu** [comment]
npm status is updated: https://status.npmjs.org/incidents/gzg16mxb67nw

**Comment by fengmk2** [comment]
fixed now https://status.npmjs.org/incidents/gzg16mxb67nw
