### ISSUE TITLE
Successfully publish to npm but unable to download

### ISSUE THREAD

**Issue by kmsheng** [npm/registry-issue-archive#381]
as title
![screen shot 2018-08-07 at 1 25 02 pm](https://user-images.githubusercontent.com/880569/43756039-751340a4-9a45-11e8-84b9-48279f221e98.png)

![screen shot 2018-08-07 at 1 25 09 pm](https://user-images.githubusercontent.com/880569/43756029-5f8520ae-9a45-11e8-9534-d16a98bec5ea.png)

**Comment by jefflembeck** [comment]
Sorry about this. We have an ongoing issue here: https://status.npmjs.org/incidents/gzg16mxb67nw

This is a duplicate issue of #379
