### ISSUE TITLE
version prop on a package:publish event

### ISSUE THREAD

**Issue by bassjacob** [npm/registry-issue-archive#43]
Hi,

I'm really happy about this feature, thanks for working on it :smile: 

I'm not sure if what I'm noticing is a bug, but when publishing a package the event payload consistently is of the format `{"event":"package:change","name":"@scope/name","type":"package","version":"1.0.0", ...` regardless of what version has actually been published. The version in the payload is always 1.0.0.

Is this expected? If so, should I be matching on the dist-tags: { "latest" } prop?

**Comment by soldair** [comment]
interesting. sounds like a bug.
ill take a look and come back with more questions if needed.

i believe we still have a bug where the first time a package is published or changed in any way after creating the webhook the event is always package:change because we dont have a previous verison to compare it against.

**Comment by bassjacob** [comment]
Super quick response, thanks! :smile: 

This might be unrelated to that, I've seen the result a few times not only after the first publish or change. I did encounter the package:change "bug" on the first run but I'm seeing package:publish events now.

**Comment by soldair** [comment]
as @nexdrew pointed out.
the version property is the payload envelope version. not the module version. 

when the event is package:publish you should see metadata data for the change. if the event type is package:change you have to do some inferring yourself atm to reason ablout what the change was.

**Comment by soldair** [comment]
if you dont know the documentation for the hook event payloads are here 
https://github.com/npm/registry/blob/master/docs/hooks/hooks-payload.md

**Comment by bassjacob** [comment]
Got it, that makes more sense. Thanks for taking a look, I'll work off that document. :+1:
