### ISSUE TITLE
exclamation point in package name makes publish hang

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/registry-issue-archive#48]
<img width="822" alt="screen shot 2016-08-26 at 3 23 21 pm" src="https://cloud.githubusercontent.com/assets/1163554/18017830/71dad89a-6ba1-11e6-9dd4-4540a10caaf8.png">

**Comment by silkentrance** [comment]
@ashleygwilliams why would you want an exclamation mark in your package name? next there would be hello!!!!1, or even !!!1111111111hello. We do not want that yellow page junk in npm.

**Comment by silkentrance** [comment]
@isaacs please close as this is unwanted and absolutely irrelevant. thanks!

**Comment by isaacs** [comment]
@silkentrance Thank you for your enthusiasm.  Whether it's desirable or not to have `!` characters in a package name, it should not _hang_, so this was definitely a bug.

As it happens, it was fixed at some point, and now fails fast, as it should:

```
$ npm publish
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 Registry returned 404 for PUT on https://registry.npmjs.org/!exclaim!
npm ERR! 404
npm ERR! 404  '!exclaim!' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
```

Weird that it fails with a 404, though.

**Comment by silkentrance** [comment]
@isaacs thanks for further investigation and hopefully fixing the 404 issue and making this a proper error response.
