### ISSUE TITLE
Does replicate.npmjs.com support `limit`?

### ISSUE THREAD

**Issue by kemitchell** [npm/registry-issue-archive#52]
The [CouchDB replication protocol](http://docs.couchdb.org/en/stable/api/database/changes.html) describes a `limit` query parameter to limit the number of changes served in response to a request. However

```
curl -H "Accept: application/json" "https://replicate.npmjs.com/_changes?limit=5"
```

and similar stream all available records, without limit.

My goal was to try replication in a "pull" style, rather than the default "push" style. The "pull" style would be useful for followers that do a lot of work per change.

Does replicate.npmjs.com support limited queries?

Forgive me if I'm missing something obvious. This is maybe my second or third time dealing with CouchDB replication directly.

**Comment by soldair** [comment]
I'm not sure the status of limit but im curious about your implementation.
if you pause a stream it should stop reading data off the tcp socket until you resume.
are you using a module like changes-stream to process items?

**Comment by kemitchell** [comment]
Thanks for responding!

I've used `changes-stream`, with `pump` and streams all the way down. I understand that's the blessed way to interact with the replication API in the default, flowing way.

The question about limit was more in the nature of an experiment. I'm running into memory, GC, and disk throughput issues. So I'm poking around, swapping some components in and out, and taking some measurements. I suspect the memory and GC issues have something to do with lots of streams---default and object mode---filling lots of buffers.

But that's all rather specific to my project.

**Comment by mmalecki** [comment]
Hey @kemitchell,

Turns out we don't support that option yet! It seems like a really easy fix however, so I'll let you know when it's deployed.

**Comment by mmalecki** [comment]
@kemitchell This should be fixed now!

```
➜  ~ curl https://replicate.npmjs.com/_changes\?since\=3105680\&limit\=4\&feed\=continuous
{"id":"dinosaur-fetcher","seq":3105681,"changes":[{"rev":"6-e0c0a7702f8dd98eba98a2f3e04913b1"}]}
{"id":"weboptimizer","seq":3105682,"changes":[{"rev":"1-cb2abfb3fc48c27bae647652924855e8"}]}
{"id":"seneca-joi","seq":3105683,"changes":[{"rev":"7-56b33dfd869dd7b8db8c0ce89ee110a1"}]}
{"id":"ether-commando","seq":3105684,"changes":[{"rev":"5-38743f7202294fa8a2b55ac5ad4dd2a7"}]}
{"last_seq":3105684}
```

Let me know if it works for you.

**Comment by kemitchell** [comment]
Thanks!

**Comment by kemitchell** [comment]
Not totally unrelated note: It appears some if not all of my memory woes were the result of stream buffers flooding with massive `include_docs` updates. Some of the packages in the registry have hundreds of versions---I suspect CI autodeploy at work---with several KB of README and other text in meta. GC is doing much better work for me now that I've set `highWaterMark`s low.

It's on my list to write an analog to `changes-stream` that uses `limit` to feed a [pull-stream](https://npmjs.com/package/pull-stream).

I'm going to go ahead and close. Y'all have enough to deal with here on the repo.
