### ISSUE TITLE
Include 'status' of package in 'view' results

### ISSUE THREAD

**Issue by orin-fink** [npm/registry-issue-archive#53]
It would be ideal if when getting a list of packages the status (active vs. deprecated) would be identified in the results.

The use case for me is that I am building a dynamic list of 'version options' for a user to select when choosing versions to be used in their project.  I would love to be able to show only the versions that are NOT deprecated by making a single call.  As it stands today, we need to first make a call to get the list of all versions, then, make another call to each version and find out if it has the deprecated node in the result or not.

**Comment by soldair** [comment]
interesting. what urls are you using to pull the data? I'm sure the depricated property is already on each version in the full metadata. There should be no reason to ever have to pull by version. Maybe im misunderstanding the request?

```
curl https://registry.npmjs.org/mongodb | json_pp | grep deprecated
```

prints

```
         "deprecated" : "please use 2.0.1 or higher",
         "deprecated" : "Upgrade to 1.4.15 due to bugs",
         "deprecated" : "Version is deprecated due to bug",
         "deprecated" : "Upgrade to 1.4.18 or higher",
         "deprecated" : "Move to 2.0.2 due to dependency issue with bson",
         "deprecated" : "problem with listCollections command, use 1.4.23 or > 1.4.25",
```

the property is 
module.version[version].deprecated

**Comment by orin-fink** [comment]
Oh, i was just using `npm view {package} versions`  and then `npm view {package}@{version}`

**Comment by soldair** [comment]
you may just want to curl the endpoint. we will suport that kind of request forever.

https://registry.npmjs.org/{modulename}

if you would like npm view output to be changed perhaps propose it as a feature request or pull request on the cli repo https://github.com/npm/npm/issues

**Comment by orin-fink** [comment]
OK, cool.  Although... i was just trying to curl against my scoped (public) package and getting not found.  Anything special about scoped packages to look out for?

**Comment by soldair** [comment]
i think this works

```
curl -H 'Authorization: Bearer {auth token from ~/.npmrc}' https://registry.npmjs.org/@scope%2fmodulename
```

**Comment by orin-fink** [comment]
Ahh, got it... URL encoding.   https://registry.npmjs.org/@scope%2fpackage

**Comment by soldair** [comment]
you only need the token if it's private

**Comment by orin-fink** [comment]
sweet, all good! thanks @soldair !

**Comment by soldair** [comment]
ok ill close this for now. please open again if you have any more questions
