### ISSUE TITLE
Company Wide Local-Registry

### ISSUE THREAD

**Issue by JeremyCarlsten** [npm/registry-issue-archive#62]
Hopefully I've found the correct npm section. The company I'm employed at is looking to use our existing [nexus](https://books.sonatype.com/nexus-book/3.0/reference/npm.html#npm-proxying-registries) repository to mirror the npm packages. However, our local nexus repo uses https and Certificates.  
I've tried setting the cafile property in the npm config, but I'm still getting a 
 "will retry, error on last attempt: Error: self signed certificate in certificate chain"
error. 

Is there something obvious I'm missing, or some docs on this that I didn't find in my googling?

**Comment by soldair** [comment]
we don't provide support for nexus but here is the documentation for the cafile npmrc config https://docs.npmjs.com/misc/config#cafile

if setting this to a file that exists with the correct data doesnt work you may need to open an issue on the cli repo https://github.com/npm/npm/issues

this is a repository for capturing issues related to the public npm registry (https://registry.npmjs.org) and npm enterprise (https://www.npmjs.com/enterprise)

**Comment by JeremyCarlsten** [comment]
In case someone else comes across this problem these keys need to be set in your .npmrc file.

```
registry=<path to your mirror>
ca=
cafile=<path to your .crt file>
_auth=<base64Encode(username:password)> 
always-auth=true
```

**Comment by soldair** [comment]
glad you figured it out :heart:
