### ISSUE TITLE
Package out of sync in skimdb

### ISSUE THREAD

**Issue by DimitryDushkin** [npm/registry-issue-archive#64]
Min-document's current version is [2.19.0](https://www.npmjs.com/package/min-document), but skimdb has only [2.18.1](https://skimdb.npmjs.com/registry/min-document).

This breaks builds with local npm registry use.

**Comment by soldair** [comment]
please see https://github.com/npm/registry/issues/57
we are actively working on this and will update this issue as it's resolved.
