### ISSUE TITLE
Registry & SkimDB versions are not in sync

### ISSUE THREAD

**Issue by krotscheck** [npm/registry-issue-archive#7]
According to https://github.com/npm/npm/issues/9701, 'recently'(?) the npm client started to correct semver versions on publish. For versions published previous to that date, it appears that the registry docs were updated and sanitized. This sanitization step does not appear to have happened for the skimdb registry, resulting in the fact that the databases are advertising different versions.

Example below, note that the registry publishes versions `1.0.2-beta`, vs skimdb's publishing of `1.0.2beta`.

```
> curl https://registry.npmjs.org/handlebars > handlebars_registry.json
> curl https://skimdb.npmjs.com/registry/handlebars > handlebars_skimdb.json

-------------------------

> var h1 = require('./handlebars_registry.json');
undefined
> var h2 = require('./handlebars_skimdb.json');
undefined
> Object.keys(h1.versions);
[ '1.0.6',
  '1.0.6-2',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.0.10',
  '1.0.11',
  '1.0.12',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '2.0.0-alpha.1',
  '2.0.0-alpha.2',
  '2.0.0-alpha.3',
  '2.0.0-alpha.4',
  '2.0.0-beta.1',
  '2.0.0',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '4.0.0',
  '4.0.1',
  '4.0.2',
  '4.0.3',
  '4.0.4',
  '4.0.5',
  '1.0.2-beta',
  '1.0.4-beta',
  '1.0.5-beta' ]
> Object.keys(h2.versions);
[ '1.0.2beta',
  '1.0.4beta',
  '1.0.5beta',
  '1.0.6',
  '1.0.6-2',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.0.10',
  '1.0.11',
  '1.0.12',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '2.0.0-alpha.1',
  '2.0.0-alpha.2',
  '2.0.0-alpha.3',
  '2.0.0-alpha.4',
  '2.0.0-beta.1',
  '2.0.0',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '4.0.0',
  '4.0.1',
  '4.0.2',
  '4.0.3',
  '4.0.4',
  '4.0.5' ]
```

**Comment by soldair** [comment]
We have a module! =) https://github.com/npm/normalize-registry-metadata
run this to clean each doc as you get them from skimdb. 

I'm pretty sure a feed will become available as part of or official api which will serve these cleaned documents.

**Comment by soldair** [comment]
note that this module also fixes errors where versions as the doc.time keys are not cleaned by the current registry. So if you use this module you will be able to join doc.time[version] to doc.versions[version]

**Comment by krotscheck** [comment]
Nice. That helps us, though having the master source be reliable would be far preferable. What's the ETA on getting a sane update feed?

**Comment by soldair** [comment]
I agree. We use this module in a number of places in production though and its very reliable. 
we don't have a set in stone ETA but something we are actively working on should fit this purpose.

Also if you haven't seen https://github.com/npm/concurrent-couch-follower this is the module we recommend for streaming changes from skimdb.

**Comment by terinjokes** [comment]
@soldair It's worth nothing that joining might not be perfect. `normalize-registry-metadata` does not correct the `doc.time` key if the unclean version had already been unpublished (and thus missing from `doc.versions`).

**Comment by soldair** [comment]
Thanks. Seems like we should clean it regardless then. The inner join is perfect but the outer join is a bit... odd.  I'll fix it Monday if no one else prs it first :)
