### ISSUE TITLE
data lost on replicate.npmjs.com

### ISSUE THREAD

**Issue by fengmk2** [npm/registry-issue-archive#70]
I just found replicate.npmjs.com is empty now.

e.g.: https://replicate.npmjs.com/koa

``` json
{
  "error": "not_found",
  "reason": "no_db_file"
}
```

**Comment by fengmk2** [comment]
ping @soldair

**Comment by fengmk2** [comment]
I found registry router change to https://replicate.npmjs.com/registry/koa

**Comment by soldair** [comment]
Yeah it requires the /registry chunk now this was an unintentional change in the scaling work we just completed

**Comment by nexdrew** [comment]
Thanks to @mmalecki, we have patched this unintentional change, at least temporarily. You may now use either `https://replicate.npmjs.com` _or_ `https://replicate.npmjs.com/registry` as the base URL for a follower (or CouchDB replication in general) - both should now work.

Note that, as of [this announcement on October 21st](http://status.npmjs.org/incidents/tnqs3k0vrwrm), the sequence history for replication was reset, so followers should reset their sequence number accordingly.

**Comment by fengmk2** [comment]
Thanks! It's work now!
