### ISSUE TITLE
'cached-path-relative' is not in the npm registry.

### ISSUE THREAD

**Issue by jglynn43** [npm/registry-issue-archive#71]
This is a dependency for module-deps. I keep getting this error as of today when rebuilding my local repository: npm ERR! 404  'cached-path-relative' is not in the npm registry.

**Comment by soldair** [comment]
do you have any custom registry configuration? this is certainly in the registry. if you're seeing a 404 your registry config may not be pointing to https://registry.npmjs.org

`npm config get registry` to print the current value. 

If you like, you may link your npm-debug.log as a gist and or email support@npmjs.com so we can dig in a little more.

**Comment by jglynn43** [comment]
My registry is https://npm.platforms.engineering/

here is a portion of the debug log:

`634 silly fetchPackageMetaData Error: failed to proxy package JSON from remote : cached-path-relative
634 silly fetchPackageMetaData     at makeError (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
634 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
634 silly fetchPackageMetaData     at Request._callback (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
634 silly fetchPackageMetaData     at Request.self.callback (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:187:22)
634 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
634 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
634 silly fetchPackageMetaData     at Request.<anonymous> (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:1044:10)
634 silly fetchPackageMetaData     at emitOne (events.js:77:13)
634 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
634 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/jjglyn/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/request/request.js:965:12)
634 silly fetchPackageMetaData  error for cached-path-relative@^1.0.0 { [Error: failed to proxy package JSON from remote : cached-path-relative] pkgid: 'cached-path-relative', statusCode: 404, code: 'E404' }
`

**Comment by soldair** [comment]
you are definitely not using the public registry. looks like some kind of mirror? 
please run `npm config set registry https://registry.npmjs.org` to set your npm to the public registry.

But there is probably a reason why you are running your own mirror. If you are running npm enterprise you can file a support request and we can give you a hand. Otherwise I would check that your registry is replicating correctly. I see a document count of only `,"doc_count":7073` when it should be `"doc_count":414080,`

**Comment by jglynn43** [comment]
That's quite a difference. I am able to get module-deps installed with the other registry. I'm going to have to get with our Ops guys and see what the issue is and if we need a support request. Thanks for your help and I'll close this.
