### ISSUE TITLE
Error 504 when trying to fetch radiokit-toolkit-streaming 0.0.8

### ISSUE THREAD

**Issue by mspanc** [npm/registry-issue-archive#72]
I get Error 504 when trying to fetch radiokit-toolkit-streaming 0.0.8

This URL https://registry.npmjs.org/radiokit-toolkit-streaming/-/radiokit-toolkit-streaming-0.0.8.tgz

returns `{"code":"InternalError","message":"Cannot read property '0.0.8' of undefined"}`

**Comment by soldair** [comment]
ill take a look at this. i dont seem to be having any issues pulling this tarball myself but ill verify it exists on all the package servers in all the right places.

**Comment by soldair** [comment]
i see a packages server in eu got behind and have fixed the issue. please let me know if its working for you now

**Comment by mspanc** [comment]
Now works, thanks!
