### ISSUE TITLE
Registry replication deprecation

### ISSUE THREAD

**Issue by gforceg** [npm/registry-issue-archive#74]
Greetings!

I am trying to convince my boss to setup an internal npm registry as described here: [https://github.com/npm/npm-registry-couchapp](https://github.com/npm/npm-registry-couchapp). But the instructions are deprecated.

Our goal is to publish packages internally and still install packages from the public npm repo and it seems the process described in the above instructions will allow us to do that.

Will there be a point at which our internal repo breaks due to changes in the npm registry or the npm client? Will there be documentation with instructions before the above process breaks so that we can adapt to npm's emerging APIs? Are there other questions I should be asking?

Thanks!

**Comment by soldair** [comment]
there are a number of commands and npm features that no longer work just with the couchapp. its been deprecated for a long time as we had to change architecture to support the growing demand on the registry services. I dont recommend using it as a private npm registry

Perhaps our orgs or enterprise appliance would be a good fit for your team. https://www.npmjs.com/enterprise

**Comment by soldair** [comment]
oh. i forgot to mention that both of these services support private modules and can still install public modules the difference between orgs and enterprise is that enterprise runs within your firewall.
