### ISSUE TITLE
npm -g install chromedriver@2.19.0 issue

### ISSUE THREAD

**Issue by tomliuxin** [npm/registry-issue-archive#76]
C:\Users\sqlcl02>npm -g install chromedriver@2.19.0
npm ERR! fetch failed https://registry.npmjs.org/chromedriver/-/chromedriver-2.19.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/chromedriver/-/chromedriver-2.19.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
[    ..............] / loadRequestedDeps: WARN retry will retry, error on last attempt: Error: fetch failed with status

**Comment by aksharpatel47** [comment]
This is not limited to chromedriver. I'm getting this while installing all dependencies.

**Comment by tomliuxin** [comment]
@aksharpatel47  Yes, maybe due to the npm server down?
