### ISSUE TITLE
Unable to star/unstar a scoped package with public access

### ISSUE THREAD

**Issue by CedX** [npm/registry-issue-archive#79]
See: https://github.com/npm/npm/issues/14526

One week later, the issue is still here, with the same symptoms.

**Comment by soldair** [comment]
interesting. thanks for reporting! 
we'll take a look and let you know.

**Comment by soldair** [comment]
found the source of this issue. we'll be releasing this fix soon.

**Comment by CedX** [comment]
Thanks 😄

**Comment by soldair** [comment]
released the fix and tested. thanks for reporting!
