### ISSUE TITLE
US POP (SF) returning bad JSON data

### ISSUE THREAD

**Issue by kaimallea** [npm/registry-issue-archive#82]
Hi, a specific US POP (151.101.32.162) appears to be returning bad JSON data for a specific package's dependency:

```
npm install gulp.spritesmith
...
npm http 200 https://registry.npmjs.org/extsprintf/1.0.2
npm ERR! registry error parsing json
```
We are using npm `1.3.10` included with Ubuntu Trusty in this particular instance and cannot easily upgrade npm as a workaround.

If I edit my `/etc/hosts` file and force `registry.npmjs.org` to another IP/POP, the problem goes away: `23.235.39.162 registry.npmjs.org`

I found this workaround in an old issue, but it is not easy/convenient in an automation environment (ci, jenkins, etc): https://github.com/npm/npm/issues/9574#issuecomment-139940172

**Comment by soldair** [comment]
thanks for reporting this. ill take a look now

**Comment by soldair** [comment]
i purged the route in question and i see that its returning the expected result. With the correct vary header and returns json. thanks for reporting!
