### ISSUE TITLE
NPM Registry dependency installs result in HTTP:404

### ISSUE THREAD

**Issue by heatmonkey** [npm/registry-issue-archive#85]
Doing a normal NPM install on the build server, started doing this.

[09:57:12][Exec] npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz
[09:57:12][Exec] npm WARN retry will retry, error on last attempt fetch failed with status code 404
[09:57:23][Exec] npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz
[09:57:23][Exec] npm WARN retry will retry, error on last attempt fetch failed with status code 404
[09:58:24][Exec] npm ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz

**Comment by soldair** [comment]
ill take a look thanks for reporting.

**Comment by soldair** [comment]
i see this new version was published only an hour ago. ill get to the bottom of it.

```
  "3.2.0" : "2016-11-17T16:46:03.350Z",
```

**Comment by heatmonkey** [comment]
https://github.com/kangax/html-minifier/issues/747
https://github.com/kangax/html-minifier/issues/745

this might be related.

**Comment by soldair** [comment]
@heatmonkey if you `npm cache clear` and `npm install` their unpublish fix should resolve it for you for now. 

im looking into what happend with those publishes now.

**Comment by alexlamsl** [comment]
FWIW I have unpublished `3.2.1` and `3.2.0` so people can get on with their day jobs with the previous version of `html-minifier`.

One interesting thing I observed was when I published `3.2.1` in the hopes of working around this issue, I can `npm install` it for the first few minutes before subsequent attempts all ending up in 404s.

`npm cache clean` is always run before any `npm install` attemps.

**Comment by soldair** [comment]
ok thanks for the info. ill ping you if i need any other details or when i figure it out.

**Comment by soldair** [comment]
@alexlamsl you were using the standard npm client right? not yarn?

**Comment by alexlamsl** [comment]
@soldair indeed. I just run `npm publish` from Command Prompt with a standard Node.js installation.

**Comment by soldair** [comment]
looking into https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz as well

**Comment by soldair** [comment]
this was repaired. https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz

**Comment by alexlamsl** [comment]
@soldair I went ahead and published `html-minifier` 3.2.0 as 3.2.2, and so far looking good. Personally I would prefer having 3.2.0 back, but I guess it's not a big deal either way.

**Comment by soldair** [comment]
sorry for the issue and thank you for using a new patch version. it saves me from having to do some unsafe data manipulation i rather try to avoid at all costs. 

ill verify everything made it to where it was supposed to go then close this issue.

**Comment by soldair** [comment]
it made it. =)
thanks agian for your help in debugging this issue. if you run into anything like this again dont hesitate to open an issue on this tracker.

**Comment by alexlamsl** [comment]
Thanks for sorting this out :wink:
