### ISSUE TITLE
Registry fetch failed 404

### ISSUE THREAD

**Issue by pepper** [npm/registry-issue-archive#86]
Error Message:

npm install redux-persist
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "redux-persist"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

And when visit:
https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz

I got:
http://imgur.com/a/s8ufn

And here have more info:
[redux-persist #212](https://github.com/rt2zz/redux-persist/issues/212)
[npm #14646](https://github.com/npm/npm/issues/14646#issuecomment-261308454)

**Comment by soldair** [comment]
this is good to go.
