### ISSUE TITLE
replicate package version is wrong

### ISSUE THREAD

**Issue by fengmk2** [npm/registry-issue-archive#87]
see https://replicate.npmjs.com/shelljs

version should be `0.0.6-pre2`, but now become `0.0.6pre2`

![image](https://cloud.githubusercontent.com/assets/156269/20417309/6ae2c0aa-ad7f-11e6-8fdf-f9b99f9d15ea.png)

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/20417593/7faf1e64-ad81-11e6-8460-7f16e37814d0.png)
![image](https://cloud.githubusercontent.com/assets/1147375/20417597/8943e978-ad81-11e6-8f7c-64d818105c2e.png)

https://replicate.npmjs.com/shelljs
https://registry.npmjs.com/shelljs

**Comment by soldair** [comment]
Please run normalize-registry-metadata on the documents you pull and it'll fix them right up. 

We do this on documents from couchdb before we serve them from registry.npmjs.org

**Comment by bcoe** [comment]
@soldair @fengmk2 `skimdb.npmjs.com`, and `replicate.npmjs.com`, both have npm's legacy [npm-registry-couchapp](https://github.com/npm/npm-registry-couchapp) installed. Another option, other than running it through a normalize step, is to set the host header to `registry.npmjs.org` -- which will apply some normalization for you.

`curl -XGET https://replicate.npmjs.com/shelljs -H "Host: registry.npmjs.org" | json versions`

**Comment by fengmk2** [comment]
I google and found the blog post http://blog.npmjs.org/post/142077474335/npm-registry-is-now-fully-https

**Comment by fengmk2** [comment]
@bcoe `time` property not work on you way. I will use `normalize-registry-metadata` to fix this problem.

![image](https://cloud.githubusercontent.com/assets/156269/20422022/ad189c42-ada2-11e6-9477-300ea6ee10e6.png)
