### ISSUE TITLE
How are we supposed to get out dated packages updated?

### ISSUE THREAD

**Issue by danshome** [npm/registry-issue-archive#94]
As an example, angular-selectize2 (https://libraries.io/search?q=angular-selectize2) is at version v3.0.1 all other repos, but NPM's repo still has an old version.   We don't want to move to bower, so what is the proper channel for getting an out of date package updated if the original publisher is no longer keeping things updated on NPM?

**Comment by soldair** [comment]
You should get in contact with the author either by creating an issue on their github repo or emailing them.

Either ask them to update (very nicely), or if they are no longer interested in the project, they may be interested in transfering it to you.

In the mean time if you can find the new code you could fork it and publish it as a public scoped module prefixed by your npm username. @danshome/angular-selectize2

**Comment by danshome** [comment]
The original authors aren't responding to any emails or requests, as you can see looking at their issues people have been posting issues and even a request to have them update npm, but all requests are going unanswered.  https://github.com/machineboy2045/angular-selectize/issues/117

 What next?
 
We don't want to create custom versions just because the author isn't updating NPM.  If github has a new release and bower has the latest release but NPM doesn't, why would NPM want to allow an author to do this? Do you not have any policies in place that state if someone publishes a package to NPM and then releases a new version that they are obligated to keep it updated?  If not, in the end the only people hurt by this would seem to be NPM because it gives people the impression that the NPM registry isn't maintained.

**Comment by soldair** [comment]
i believe this falls under our dispute policy please check it out. 
https://www.npmjs.com/policies/disputes

**Comment by danshome** [comment]
I sent an email to abuse@npmjs.com.

**Comment by danshome** [comment]
@soldair This is still an issue.  What's the latest with my dispute?

**Comment by soldair** [comment]
ping support@npmjs.com if you have any questions.
